-- The mod's default deck (2026-10-08, the author: "make my current deck and options the default (87 cards in the draw)"):
-- every setting of every card of the author's own deck, and the order and sort of the Deck, written from their settings on
-- that day (tools: the scratchpad's gen_defaults.py read user_settings.config). GrandfathersTarot.lua seeds them on a fresh
-- install; Events.reset (a card's Reset, Restore defaults, an empty preset) gives a card these values back. The options'
-- defaults are in GrandfathersTarot_data.lua.
-- One assignment per line, not one table literal: LuaJIT reports a table literal as a single line, so a 1,800-line literal
-- read as uncovered there (the coverage gate runs on Lua 5.5 and LuaJIT).
local UserDefaults = {}

UserDefaults.CARD_PREFIXES = { "wave_def_", "on_", "pct_", "su_", "th_", "cd_", "wh_", "sp_", "snd_", "fx_", "dmin_", "dmax_", "ev_", "rf_", "re_", "cl_", "rk_", "del_" }

local deck = {}
deck.deck_order = "custom_46,custom_50,custom_70,custom_73,custom_47,custom_34,custom_26,custom_49,custom_42,custom_36,custom_67,custom_38,custom_68,custom_23,custom_35,custom_41,custom_27,custom_39,custom_69,custom_17,custom_25,custom_22,custom_76,custom_21,custom_28,custom_29,custom_48,custom_66,custom_55,custom_24,custom_53,custom_1,custom_7,custom_6,custom_54,bomber_frenzy,ogryn_brutes,custom_75,custom_63,custom_18,custom_51,custom_37,custom_58,custom_16,custom_13,custom_12,custom_33,custom_31,custom_45,sniper_elite,custom_14,custom_2,custom_61,custom_60,wave_small,custom_64,custom_44,boss_ambush,custom_8,custom_74,wave_large,custom_65,custom_56,custom_9,wave_medium,custom_59,custom_11,custom_15,custom_19,custom_62,elite_squad,custom_32,custom_30,special_pack,custom_3,custom_20,custom_10,hound_frenzy,custom_5,custom_40,custom_71,custom_43,custom_4,custom_57,custom_52,grenade_legion,custom_72,wave_huge,custom_77,custom_78,custom_79,custom_80,custom_81,custom_82,custom_83,custom_84,custom_85,custom_86,custom_87,custom_88"
deck.deck_sort = "face"
deck.deck_sort_desc = true
deck.picker_stay = false
deck.shelf_faction = "dreg"
UserDefaults.deck = deck

local cards = {}
cards.cd_bomber_frenzy = 270
cards.cd_boss_ambush = 240
cards.cd_custom_1 = 600
cards.cd_custom_10 = 120
cards.cd_custom_11 = 300
cards.cd_custom_12 = 300
cards.cd_custom_13 = 300
cards.cd_custom_14 = 300
cards.cd_custom_15 = 600
cards.cd_custom_16 = 150
cards.cd_custom_17 = 1800
cards.cd_custom_18 = 420
cards.cd_custom_19 = 480
cards.cd_custom_2 = 240
cards.cd_custom_20 = 300
cards.cd_custom_21 = 1200
cards.cd_custom_22 = 1500
cards.cd_custom_23 = 1200
cards.cd_custom_24 = 360
cards.cd_custom_25 = 1800
cards.cd_custom_26 = 300
cards.cd_custom_27 = 600
cards.cd_custom_28 = 1200
cards.cd_custom_29 = 1200
cards.cd_custom_3 = 600
cards.cd_custom_30 = 300
cards.cd_custom_31 = 300
cards.cd_custom_32 = 300
cards.cd_custom_33 = 300
cards.cd_custom_34 = 300
cards.cd_custom_35 = 630
cards.cd_custom_36 = 1200
cards.cd_custom_37 = 300
cards.cd_custom_38 = 300
cards.cd_custom_39 = 1200
cards.cd_custom_4 = 300
cards.cd_custom_40 = 300
cards.cd_custom_41 = 900
cards.cd_custom_42 = 1080
cards.cd_custom_43 = 300
cards.cd_custom_44 = 600
cards.cd_custom_45 = 300
cards.cd_custom_46 = 1500
cards.cd_custom_47 = 600
cards.cd_custom_48 = 1200
cards.cd_custom_49 = 300
cards.cd_custom_5 = 300
cards.cd_custom_50 = 1500
cards.cd_custom_51 = 300
cards.cd_custom_52 = 300
cards.cd_custom_53 = 300
cards.cd_custom_54 = 300
cards.cd_custom_55 = 480
cards.cd_custom_56 = 300
cards.cd_custom_57 = 300
cards.cd_custom_58 = 300
cards.cd_custom_59 = 300
cards.cd_custom_6 = 240
cards.cd_custom_60 = 240
cards.cd_custom_61 = 720
cards.cd_custom_62 = 420
cards.cd_custom_63 = 900
cards.cd_custom_64 = 420
cards.cd_custom_65 = 300
cards.cd_custom_66 = 900
cards.cd_custom_67 = 600
cards.cd_custom_68 = 600
cards.cd_custom_69 = 480
cards.cd_custom_7 = 300
cards.cd_custom_70 = 1800
cards.cd_custom_71 = 600
cards.cd_custom_72 = 300
cards.cd_custom_73 = 900
cards.cd_custom_74 = 300
cards.cd_custom_75 = 120
cards.cd_custom_76 = 1500
cards.cd_custom_77 = 120
cards.cd_custom_78 = 120
cards.cd_custom_79 = 120
cards.cd_custom_8 = 300
cards.cd_custom_80 = 120
cards.cd_custom_81 = 120
cards.cd_custom_82 = 120
cards.cd_custom_83 = 120
cards.cd_custom_84 = 120
cards.cd_custom_85 = 120
cards.cd_custom_86 = 120
cards.cd_custom_87 = 120
cards.cd_custom_88 = 120
cards.cd_custom_9 = 300
cards.cd_elite_squad = 300
cards.cd_grenade_legion = 300
cards.cd_hound_frenzy = 210
cards.cd_ogryn_brutes = 300
cards.cd_sniper_elite = 300
cards.cd_special_pack = 300
cards.cd_wave_huge = 240
cards.cd_wave_large = 300
cards.cd_wave_medium = 180
cards.cd_wave_small = 240
cards.cl_bomber_frenzy = ""
cards.cl_boss_ambush = ""
cards.cl_custom_1 = ""
cards.cl_custom_10 = ""
cards.cl_custom_11 = ""
cards.cl_custom_12 = ""
cards.cl_custom_13 = ""
cards.cl_custom_14 = ""
cards.cl_custom_15 = ""
cards.cl_custom_16 = ""
cards.cl_custom_17 = ""
cards.cl_custom_18 = ""
cards.cl_custom_19 = ""
cards.cl_custom_2 = ""
cards.cl_custom_20 = ""
cards.cl_custom_21 = "rot"
cards.cl_custom_22 = "rot"
cards.cl_custom_23 = ""
cards.cl_custom_24 = ""
cards.cl_custom_25 = ""
cards.cl_custom_26 = ""
cards.cl_custom_27 = ""
cards.cl_custom_28 = ""
cards.cl_custom_29 = ""
cards.cl_custom_3 = ""
cards.cl_custom_30 = ""
cards.cl_custom_31 = ""
cards.cl_custom_32 = ""
cards.cl_custom_33 = ""
cards.cl_custom_34 = ""
cards.cl_custom_35 = ""
cards.cl_custom_36 = ""
cards.cl_custom_37 = ""
cards.cl_custom_38 = ""
cards.cl_custom_39 = ""
cards.cl_custom_4 = ""
cards.cl_custom_40 = ""
cards.cl_custom_41 = ""
cards.cl_custom_42 = ""
cards.cl_custom_43 = ""
cards.cl_custom_44 = ""
cards.cl_custom_45 = ""
cards.cl_custom_46 = ""
cards.cl_custom_47 = ""
cards.cl_custom_48 = ""
cards.cl_custom_49 = ""
cards.cl_custom_5 = ""
cards.cl_custom_50 = ""
cards.cl_custom_51 = ""
cards.cl_custom_52 = ""
cards.cl_custom_53 = ""
cards.cl_custom_54 = ""
cards.cl_custom_55 = ""
cards.cl_custom_56 = ""
cards.cl_custom_57 = ""
cards.cl_custom_58 = ""
cards.cl_custom_59 = ""
cards.cl_custom_6 = ""
cards.cl_custom_60 = ""
cards.cl_custom_61 = ""
cards.cl_custom_62 = ""
cards.cl_custom_63 = ""
cards.cl_custom_64 = ""
cards.cl_custom_65 = ""
cards.cl_custom_66 = ""
cards.cl_custom_67 = ""
cards.cl_custom_68 = ""
cards.cl_custom_69 = ""
cards.cl_custom_7 = ""
cards.cl_custom_70 = ""
cards.cl_custom_71 = ""
cards.cl_custom_72 = ""
cards.cl_custom_73 = ""
cards.cl_custom_74 = ""
cards.cl_custom_75 = ""
cards.cl_custom_76 = ""
cards.cl_custom_77 = ""
cards.cl_custom_78 = ""
cards.cl_custom_79 = ""
cards.cl_custom_8 = ""
cards.cl_custom_80 = ""
cards.cl_custom_81 = ""
cards.cl_custom_82 = ""
cards.cl_custom_83 = ""
cards.cl_custom_84 = ""
cards.cl_custom_85 = ""
cards.cl_custom_86 = ""
cards.cl_custom_87 = ""
cards.cl_custom_88 = ""
cards.cl_custom_9 = "rot"
cards.cl_elite_squad = ""
cards.cl_grenade_legion = "vial"
cards.cl_hound_frenzy = "whisper"
cards.cl_ogryn_brutes = ""
cards.cl_sniper_elite = ""
cards.cl_special_pack = ""
cards.cl_wave_huge = ""
cards.cl_wave_large = ""
cards.cl_wave_medium = ""
cards.cl_wave_small = "rot"
cards.del_bomber_frenzy = false
cards.del_boss_ambush = false
cards.del_custom_1 = false
cards.del_custom_10 = false
cards.del_custom_11 = false
cards.del_custom_12 = false
cards.del_custom_13 = false
cards.del_custom_14 = false
cards.del_custom_15 = false
cards.del_custom_16 = false
cards.del_custom_17 = false
cards.del_custom_18 = false
cards.del_custom_19 = false
cards.del_custom_2 = false
cards.del_custom_20 = false
cards.del_custom_21 = false
cards.del_custom_22 = false
cards.del_custom_23 = false
cards.del_custom_24 = false
cards.del_custom_25 = false
cards.del_custom_26 = false
cards.del_custom_27 = false
cards.del_custom_28 = false
cards.del_custom_29 = false
cards.del_custom_3 = false
cards.del_custom_30 = false
cards.del_custom_31 = false
cards.del_custom_32 = false
cards.del_custom_33 = false
cards.del_custom_34 = false
cards.del_custom_35 = false
cards.del_custom_36 = false
cards.del_custom_37 = false
cards.del_custom_38 = false
cards.del_custom_39 = false
cards.del_custom_4 = false
cards.del_custom_40 = false
cards.del_custom_41 = false
cards.del_custom_42 = false
cards.del_custom_43 = false
cards.del_custom_44 = false
cards.del_custom_45 = false
cards.del_custom_46 = false
cards.del_custom_47 = false
cards.del_custom_48 = false
cards.del_custom_49 = false
cards.del_custom_5 = false
cards.del_custom_50 = false
cards.del_custom_51 = false
cards.del_custom_52 = false
cards.del_custom_53 = false
cards.del_custom_54 = false
cards.del_custom_55 = false
cards.del_custom_56 = false
cards.del_custom_57 = false
cards.del_custom_58 = false
cards.del_custom_59 = false
cards.del_custom_6 = false
cards.del_custom_60 = false
cards.del_custom_61 = false
cards.del_custom_62 = false
cards.del_custom_63 = false
cards.del_custom_64 = false
cards.del_custom_65 = false
cards.del_custom_66 = false
cards.del_custom_67 = false
cards.del_custom_68 = false
cards.del_custom_69 = false
cards.del_custom_7 = false
cards.del_custom_70 = false
cards.del_custom_71 = false
cards.del_custom_72 = false
cards.del_custom_73 = false
cards.del_custom_74 = false
cards.del_custom_75 = false
cards.del_custom_76 = false
cards.del_custom_77 = false
cards.del_custom_78 = false
cards.del_custom_79 = false
cards.del_custom_8 = false
cards.del_custom_80 = false
cards.del_custom_81 = false
cards.del_custom_82 = false
cards.del_custom_83 = false
cards.del_custom_84 = false
cards.del_custom_85 = false
cards.del_custom_86 = false
cards.del_custom_87 = false
cards.del_custom_88 = false
cards.del_custom_9 = false
cards.del_elite_squad = false
cards.del_grenade_legion = false
cards.del_hound_frenzy = false
cards.del_ogryn_brutes = false
cards.del_sniper_elite = false
cards.del_special_pack = false
cards.del_wave_huge = true
cards.del_wave_large = false
cards.del_wave_medium = false
cards.del_wave_small = false
cards.dmax_bomber_frenzy = 0
cards.dmax_boss_ambush = 0
cards.dmax_custom_1 = 0
cards.dmax_custom_10 = 0
cards.dmax_custom_11 = 0
cards.dmax_custom_12 = 75
cards.dmax_custom_13 = 35
cards.dmax_custom_14 = 50
cards.dmax_custom_15 = 0
cards.dmax_custom_16 = 150
cards.dmax_custom_17 = 30
cards.dmax_custom_18 = 0
cards.dmax_custom_19 = 0
cards.dmax_custom_2 = 0
cards.dmax_custom_20 = 0
cards.dmax_custom_21 = 100
cards.dmax_custom_22 = 0
cards.dmax_custom_23 = 0
cards.dmax_custom_24 = 0
cards.dmax_custom_25 = 0
cards.dmax_custom_26 = 0
cards.dmax_custom_27 = 0
cards.dmax_custom_28 = 0
cards.dmax_custom_29 = 0
cards.dmax_custom_3 = 0
cards.dmax_custom_30 = 0
cards.dmax_custom_31 = 100
cards.dmax_custom_32 = 0
cards.dmax_custom_33 = 0
cards.dmax_custom_34 = 0
cards.dmax_custom_35 = 0
cards.dmax_custom_36 = 0
cards.dmax_custom_37 = 0
cards.dmax_custom_38 = 0
cards.dmax_custom_39 = 0
cards.dmax_custom_4 = 0
cards.dmax_custom_40 = 0
cards.dmax_custom_41 = 0
cards.dmax_custom_42 = 0
cards.dmax_custom_43 = 0
cards.dmax_custom_44 = 0
cards.dmax_custom_45 = 0
cards.dmax_custom_46 = 0
cards.dmax_custom_47 = 0
cards.dmax_custom_48 = 0
cards.dmax_custom_49 = 0
cards.dmax_custom_5 = 0
cards.dmax_custom_50 = 0
cards.dmax_custom_51 = 0
cards.dmax_custom_52 = 0
cards.dmax_custom_53 = 0
cards.dmax_custom_54 = 0
cards.dmax_custom_55 = 0
cards.dmax_custom_56 = 0
cards.dmax_custom_57 = 0
cards.dmax_custom_58 = 0
cards.dmax_custom_59 = 0
cards.dmax_custom_6 = 100
cards.dmax_custom_60 = 0
cards.dmax_custom_61 = 0
cards.dmax_custom_62 = 0
cards.dmax_custom_63 = 0
cards.dmax_custom_64 = 0
cards.dmax_custom_65 = 0
cards.dmax_custom_66 = 0
cards.dmax_custom_67 = 0
cards.dmax_custom_68 = 0
cards.dmax_custom_69 = 0
cards.dmax_custom_7 = 0
cards.dmax_custom_70 = 0
cards.dmax_custom_71 = 0
cards.dmax_custom_72 = 0
cards.dmax_custom_73 = 0
cards.dmax_custom_74 = 0
cards.dmax_custom_75 = 0
cards.dmax_custom_76 = 0
cards.dmax_custom_77 = 0
cards.dmax_custom_78 = 0
cards.dmax_custom_79 = 0
cards.dmax_custom_8 = 0
cards.dmax_custom_80 = 0
cards.dmax_custom_81 = 0
cards.dmax_custom_82 = 0
cards.dmax_custom_83 = 0
cards.dmax_custom_84 = 0
cards.dmax_custom_85 = 0
cards.dmax_custom_86 = 0
cards.dmax_custom_87 = 0
cards.dmax_custom_88 = 0
cards.dmax_custom_9 = 70
cards.dmax_elite_squad = 70
cards.dmax_grenade_legion = 0
cards.dmax_hound_frenzy = 0
cards.dmax_ogryn_brutes = 0
cards.dmax_sniper_elite = 100
cards.dmax_special_pack = 0
cards.dmax_wave_huge = 0
cards.dmax_wave_large = 0
cards.dmax_wave_medium = 0
cards.dmax_wave_small = 100
cards.dmin_bomber_frenzy = 0
cards.dmin_boss_ambush = 0
cards.dmin_custom_1 = 0
cards.dmin_custom_10 = 0
cards.dmin_custom_11 = 0
cards.dmin_custom_12 = 5
cards.dmin_custom_13 = 10
cards.dmin_custom_14 = 10
cards.dmin_custom_15 = 0
cards.dmin_custom_16 = 40
cards.dmin_custom_17 = 10
cards.dmin_custom_18 = 0
cards.dmin_custom_19 = 0
cards.dmin_custom_2 = 0
cards.dmin_custom_20 = 0
cards.dmin_custom_21 = 45
cards.dmin_custom_22 = 0
cards.dmin_custom_23 = 0
cards.dmin_custom_24 = 0
cards.dmin_custom_25 = 0
cards.dmin_custom_26 = 0
cards.dmin_custom_27 = 0
cards.dmin_custom_28 = 0
cards.dmin_custom_29 = 0
cards.dmin_custom_3 = 0
cards.dmin_custom_30 = 0
cards.dmin_custom_31 = 25
cards.dmin_custom_32 = 0
cards.dmin_custom_33 = 0
cards.dmin_custom_34 = 0
cards.dmin_custom_35 = 0
cards.dmin_custom_36 = 0
cards.dmin_custom_37 = 0
cards.dmin_custom_38 = 0
cards.dmin_custom_39 = 0
cards.dmin_custom_4 = 0
cards.dmin_custom_40 = 0
cards.dmin_custom_41 = 0
cards.dmin_custom_42 = 0
cards.dmin_custom_43 = 0
cards.dmin_custom_44 = 0
cards.dmin_custom_45 = 0
cards.dmin_custom_46 = 0
cards.dmin_custom_47 = 0
cards.dmin_custom_48 = 0
cards.dmin_custom_49 = 0
cards.dmin_custom_5 = 0
cards.dmin_custom_50 = 0
cards.dmin_custom_51 = 0
cards.dmin_custom_52 = 0
cards.dmin_custom_53 = 0
cards.dmin_custom_54 = 0
cards.dmin_custom_55 = 0
cards.dmin_custom_56 = 0
cards.dmin_custom_57 = 0
cards.dmin_custom_58 = 0
cards.dmin_custom_59 = 0
cards.dmin_custom_6 = 35
cards.dmin_custom_60 = 0
cards.dmin_custom_61 = 0
cards.dmin_custom_62 = 0
cards.dmin_custom_63 = 0
cards.dmin_custom_64 = 0
cards.dmin_custom_65 = 0
cards.dmin_custom_66 = 0
cards.dmin_custom_67 = 0
cards.dmin_custom_68 = 0
cards.dmin_custom_69 = 0
cards.dmin_custom_7 = 0
cards.dmin_custom_70 = 0
cards.dmin_custom_71 = 0
cards.dmin_custom_72 = 0
cards.dmin_custom_73 = 0
cards.dmin_custom_74 = 0
cards.dmin_custom_75 = 0
cards.dmin_custom_76 = 0
cards.dmin_custom_77 = 0
cards.dmin_custom_78 = 0
cards.dmin_custom_79 = 0
cards.dmin_custom_8 = 0
cards.dmin_custom_80 = 0
cards.dmin_custom_81 = 0
cards.dmin_custom_82 = 0
cards.dmin_custom_83 = 0
cards.dmin_custom_84 = 0
cards.dmin_custom_85 = 0
cards.dmin_custom_86 = 0
cards.dmin_custom_87 = 0
cards.dmin_custom_88 = 0
cards.dmin_custom_9 = 10
cards.dmin_elite_squad = 20
cards.dmin_grenade_legion = 0
cards.dmin_hound_frenzy = 0
cards.dmin_ogryn_brutes = 0
cards.dmin_sniper_elite = 5
cards.dmin_special_pack = 0
cards.dmin_wave_huge = 0
cards.dmin_wave_large = 0
cards.dmin_wave_medium = 0
cards.dmin_wave_small = 25
cards.ev_bomber_frenzy = 0
cards.ev_boss_ambush = 0
cards.ev_custom_1 = 0
cards.ev_custom_10 = 0
cards.ev_custom_11 = 0
cards.ev_custom_12 = 0
cards.ev_custom_13 = 0
cards.ev_custom_14 = 0
cards.ev_custom_15 = 0
cards.ev_custom_16 = 0
cards.ev_custom_17 = 0
cards.ev_custom_18 = 0
cards.ev_custom_19 = 0
cards.ev_custom_2 = 0
cards.ev_custom_20 = 0
cards.ev_custom_21 = 0
cards.ev_custom_22 = 0
cards.ev_custom_23 = 0
cards.ev_custom_24 = 0
cards.ev_custom_25 = 0
cards.ev_custom_26 = 0
cards.ev_custom_27 = 0
cards.ev_custom_28 = 0
cards.ev_custom_29 = 0
cards.ev_custom_3 = 0
cards.ev_custom_30 = 0
cards.ev_custom_31 = 0
cards.ev_custom_32 = 0
cards.ev_custom_33 = 0
cards.ev_custom_34 = 0
cards.ev_custom_35 = 0
cards.ev_custom_36 = 0
cards.ev_custom_37 = 0
cards.ev_custom_38 = 0
cards.ev_custom_39 = 0
cards.ev_custom_4 = 0
cards.ev_custom_40 = 0
cards.ev_custom_41 = 0
cards.ev_custom_42 = 0
cards.ev_custom_43 = 0
cards.ev_custom_44 = 0
cards.ev_custom_45 = 0
cards.ev_custom_46 = 0
cards.ev_custom_47 = 0
cards.ev_custom_48 = 0
cards.ev_custom_49 = 0
cards.ev_custom_5 = 0
cards.ev_custom_50 = 0
cards.ev_custom_51 = 0
cards.ev_custom_52 = 0
cards.ev_custom_53 = 0
cards.ev_custom_54 = 0
cards.ev_custom_55 = 0
cards.ev_custom_56 = 0
cards.ev_custom_57 = 0
cards.ev_custom_58 = 0
cards.ev_custom_59 = 0
cards.ev_custom_6 = 0
cards.ev_custom_60 = 0
cards.ev_custom_61 = 0
cards.ev_custom_62 = 0
cards.ev_custom_63 = 0
cards.ev_custom_64 = 0
cards.ev_custom_65 = 0
cards.ev_custom_66 = 0
cards.ev_custom_67 = 0
cards.ev_custom_68 = 0
cards.ev_custom_69 = 0
cards.ev_custom_7 = 0
cards.ev_custom_70 = 0
cards.ev_custom_71 = 0
cards.ev_custom_72 = 0
cards.ev_custom_73 = 0
cards.ev_custom_74 = 0
cards.ev_custom_75 = 0
cards.ev_custom_76 = 0
cards.ev_custom_77 = 0
cards.ev_custom_78 = 0
cards.ev_custom_79 = 0
cards.ev_custom_8 = 0
cards.ev_custom_80 = 0
cards.ev_custom_81 = 0
cards.ev_custom_82 = 0
cards.ev_custom_83 = 0
cards.ev_custom_84 = 0
cards.ev_custom_85 = 0
cards.ev_custom_86 = 0
cards.ev_custom_87 = 0
cards.ev_custom_88 = 0
cards.ev_custom_9 = 0
cards.ev_elite_squad = 0
cards.ev_grenade_legion = 0
cards.ev_hound_frenzy = 0
cards.ev_ogryn_brutes = 0
cards.ev_sniper_elite = 0
cards.ev_special_pack = 0
cards.ev_wave_huge = 0
cards.ev_wave_large = 0
cards.ev_wave_medium = 0
cards.ev_wave_small = 0
cards.fx_bomber_frenzy = ""
cards.fx_boss_ambush = ""
cards.fx_custom_1 = ""
cards.fx_custom_10 = "blackout=25:4"
cards.fx_custom_11 = ""
cards.fx_custom_12 = ""
cards.fx_custom_13 = ""
cards.fx_custom_14 = ""
cards.fx_custom_15 = ""
cards.fx_custom_16 = ""
cards.fx_custom_17 = "blackout=40:4"
cards.fx_custom_18 = ""
cards.fx_custom_19 = ""
cards.fx_custom_2 = ""
cards.fx_custom_20 = ""
cards.fx_custom_21 = "blackout=60:4"
cards.fx_custom_22 = "blackout=60:4"
cards.fx_custom_23 = "revive=1:4;instant_rescue=1:4"
cards.fx_custom_24 = ""
cards.fx_custom_25 = "blackout=120:4"
cards.fx_custom_26 = "reveal=30:4"
cards.fx_custom_27 = "blue_stimm=15:4;red_stimm_buff=15:4;red_stimm_item=2:4"
cards.fx_custom_28 = "blackout=60:4"
cards.fx_custom_29 = "blackout=60:4"
cards.fx_custom_3 = ""
cards.fx_custom_30 = ""
cards.fx_custom_31 = ""
cards.fx_custom_32 = ""
cards.fx_custom_33 = ""
cards.fx_custom_34 = "ammo=35:4"
cards.fx_custom_35 = "instant_rescue=2:4"
cards.fx_custom_36 = "heal=100:4;reveal=30:4;yellow_stimm_buff=30:4;blue_stimm=30:4;red_stimm_buff=30:4"
cards.fx_custom_37 = ""
cards.fx_custom_38 = "cleanse=50:4"
cards.fx_custom_39 = "med_crate=1:4"
cards.fx_custom_4 = ""
cards.fx_custom_40 = ""
cards.fx_custom_41 = "ammo_crate=1:4"
cards.fx_custom_42 = "cleanse=100:4"
cards.fx_custom_43 = ""
cards.fx_custom_44 = ""
cards.fx_custom_45 = ""
cards.fx_custom_46 = "cleanse=100:4;instant_rescue=1:4;ammo_crate=1:4"
cards.fx_custom_47 = "grenades=2:4"
cards.fx_custom_48 = "blackout=60:4"
cards.fx_custom_49 = "reveal_elites=30:4"
cards.fx_custom_5 = ""
cards.fx_custom_50 = "yellow_stimm_buff=20:4;blue_stimm=40:4;red_stimm_buff=40:4;instant_rescue=2:4"
cards.fx_custom_51 = ""
cards.fx_custom_52 = ""
cards.fx_custom_53 = ""
cards.fx_custom_54 = ""
cards.fx_custom_55 = "blackout=60:4"
cards.fx_custom_56 = ""
cards.fx_custom_57 = ""
cards.fx_custom_58 = ""
cards.fx_custom_59 = ""
cards.fx_custom_6 = ""
cards.fx_custom_60 = ""
cards.fx_custom_61 = ""
cards.fx_custom_62 = ""
cards.fx_custom_63 = ""
cards.fx_custom_64 = ""
cards.fx_custom_65 = ""
cards.fx_custom_66 = ""
cards.fx_custom_67 = "heal=50:4;green_stimm=1:4"
cards.fx_custom_68 = "green_stimm=2:4"
cards.fx_custom_69 = "ammo=75:4"
cards.fx_custom_7 = ""
cards.fx_custom_70 = "instant_rescue=1:4;ammo=100:4;grenades=5:4"
cards.fx_custom_71 = ""
cards.fx_custom_72 = ""
cards.fx_custom_73 = "reveal=45:4;reveal_elites=45:4"
cards.fx_custom_74 = ""
cards.fx_custom_75 = ""
cards.fx_custom_76 = "blackout=120:4"
cards.fx_custom_77 = ""
cards.fx_custom_78 = ""
cards.fx_custom_79 = ""
cards.fx_custom_8 = ""
cards.fx_custom_80 = ""
cards.fx_custom_81 = ""
cards.fx_custom_82 = ""
cards.fx_custom_83 = ""
cards.fx_custom_84 = ""
cards.fx_custom_85 = ""
cards.fx_custom_86 = ""
cards.fx_custom_87 = ""
cards.fx_custom_88 = ""
cards.fx_custom_9 = ""
cards.fx_elite_squad = ""
cards.fx_grenade_legion = ""
cards.fx_hound_frenzy = ""
cards.fx_ogryn_brutes = ""
cards.fx_sniper_elite = ""
cards.fx_special_pack = ""
cards.fx_wave_huge = ""
cards.fx_wave_large = ""
cards.fx_wave_medium = ""
cards.fx_wave_small = ""
cards.on_bomber_frenzy = true
cards.on_boss_ambush = true
cards.on_custom_1 = true
cards.on_custom_10 = true
cards.on_custom_11 = true
cards.on_custom_12 = true
cards.on_custom_13 = true
cards.on_custom_14 = true
cards.on_custom_15 = true
cards.on_custom_16 = true
cards.on_custom_17 = true
cards.on_custom_18 = true
cards.on_custom_19 = true
cards.on_custom_2 = true
cards.on_custom_20 = true
cards.on_custom_21 = true
cards.on_custom_22 = true
cards.on_custom_23 = true
cards.on_custom_24 = true
cards.on_custom_25 = true
cards.on_custom_26 = true
cards.on_custom_27 = true
cards.on_custom_28 = true
cards.on_custom_29 = true
cards.on_custom_3 = true
cards.on_custom_30 = true
cards.on_custom_31 = true
cards.on_custom_32 = true
cards.on_custom_33 = true
cards.on_custom_34 = true
cards.on_custom_35 = true
cards.on_custom_36 = true
cards.on_custom_37 = true
cards.on_custom_38 = true
cards.on_custom_39 = true
cards.on_custom_4 = true
cards.on_custom_40 = true
cards.on_custom_41 = true
cards.on_custom_42 = true
cards.on_custom_43 = true
cards.on_custom_44 = true
cards.on_custom_45 = true
cards.on_custom_46 = true
cards.on_custom_47 = true
cards.on_custom_48 = true
cards.on_custom_49 = true
cards.on_custom_5 = true
cards.on_custom_50 = true
cards.on_custom_51 = true
cards.on_custom_52 = true
cards.on_custom_53 = true
cards.on_custom_54 = true
cards.on_custom_55 = true
cards.on_custom_56 = true
cards.on_custom_57 = true
cards.on_custom_58 = true
cards.on_custom_59 = true
cards.on_custom_6 = true
cards.on_custom_60 = true
cards.on_custom_61 = true
cards.on_custom_62 = true
cards.on_custom_63 = true
cards.on_custom_64 = true
cards.on_custom_65 = true
cards.on_custom_66 = true
cards.on_custom_67 = true
cards.on_custom_68 = true
cards.on_custom_69 = true
cards.on_custom_7 = true
cards.on_custom_70 = true
cards.on_custom_71 = true
cards.on_custom_72 = true
cards.on_custom_73 = true
cards.on_custom_74 = true
cards.on_custom_75 = true
cards.on_custom_76 = true
cards.on_custom_77 = true
cards.on_custom_78 = true
cards.on_custom_79 = true
cards.on_custom_8 = true
cards.on_custom_80 = true
cards.on_custom_81 = true
cards.on_custom_82 = true
cards.on_custom_83 = true
cards.on_custom_84 = true
cards.on_custom_85 = true
cards.on_custom_86 = true
cards.on_custom_87 = true
cards.on_custom_88 = true
cards.on_custom_9 = true
cards.on_elite_squad = true
cards.on_grenade_legion = true
cards.on_hound_frenzy = true
cards.on_ogryn_brutes = true
cards.on_sniper_elite = true
cards.on_special_pack = true
cards.on_wave_huge = false
cards.on_wave_large = true
cards.on_wave_medium = true
cards.on_wave_small = true
cards.pct_bomber_frenzy = 3
cards.pct_boss_ambush = 4
cards.pct_custom_1 = 2
cards.pct_custom_10 = 4
cards.pct_custom_11 = 4
cards.pct_custom_12 = 5
cards.pct_custom_13 = 6
cards.pct_custom_14 = 3
cards.pct_custom_15 = 3
cards.pct_custom_16 = 3
cards.pct_custom_17 = 1
cards.pct_custom_18 = 2
cards.pct_custom_19 = 3
cards.pct_custom_2 = 2
cards.pct_custom_20 = 4
cards.pct_custom_21 = 1
cards.pct_custom_22 = 1
cards.pct_custom_23 = 2
cards.pct_custom_24 = 5
cards.pct_custom_25 = 1
cards.pct_custom_26 = 9
cards.pct_custom_27 = 3
cards.pct_custom_28 = 1
cards.pct_custom_29 = 1
cards.pct_custom_3 = 4
cards.pct_custom_30 = 10
cards.pct_custom_31 = 6
cards.pct_custom_32 = 8
cards.pct_custom_33 = 6
cards.pct_custom_34 = 3
cards.pct_custom_35 = 5
cards.pct_custom_36 = 1
cards.pct_custom_37 = 8
cards.pct_custom_38 = 4
cards.pct_custom_39 = 3
cards.pct_custom_4 = 3
cards.pct_custom_40 = 4
cards.pct_custom_41 = 7
cards.pct_custom_42 = 2
cards.pct_custom_43 = 7
cards.pct_custom_44 = 3
cards.pct_custom_45 = 8
cards.pct_custom_46 = 1
cards.pct_custom_47 = 4
cards.pct_custom_48 = 1
cards.pct_custom_49 = 8
cards.pct_custom_5 = 9
cards.pct_custom_50 = 1
cards.pct_custom_51 = 8
cards.pct_custom_52 = 5
cards.pct_custom_53 = 3
cards.pct_custom_54 = 9
cards.pct_custom_55 = 1
cards.pct_custom_56 = 10
cards.pct_custom_57 = 6
cards.pct_custom_58 = 7
cards.pct_custom_59 = 9
cards.pct_custom_6 = 10
cards.pct_custom_60 = 4
cards.pct_custom_61 = 3
cards.pct_custom_62 = 5
cards.pct_custom_63 = 10
cards.pct_custom_64 = 5
cards.pct_custom_65 = 7
cards.pct_custom_66 = 1
cards.pct_custom_67 = 10
cards.pct_custom_68 = 7
cards.pct_custom_69 = 3
cards.pct_custom_7 = 5
cards.pct_custom_70 = 1
cards.pct_custom_71 = 3
cards.pct_custom_72 = 4
cards.pct_custom_73 = 3
cards.pct_custom_74 = 5
cards.pct_custom_75 = 10
cards.pct_custom_76 = 1
cards.pct_custom_77 = 10
cards.pct_custom_78 = 10
cards.pct_custom_79 = 10
cards.pct_custom_8 = 7
cards.pct_custom_80 = 10
cards.pct_custom_81 = 10
cards.pct_custom_82 = 10
cards.pct_custom_83 = 10
cards.pct_custom_84 = 10
cards.pct_custom_85 = 10
cards.pct_custom_86 = 10
cards.pct_custom_87 = 10
cards.pct_custom_88 = 10
cards.pct_custom_9 = 10
cards.pct_elite_squad = 6
cards.pct_grenade_legion = 7
cards.pct_hound_frenzy = 3
cards.pct_ogryn_brutes = 6
cards.pct_sniper_elite = 5
cards.pct_special_pack = 8
cards.pct_wave_huge = 1
cards.pct_wave_large = 3
cards.pct_wave_medium = 6
cards.pct_wave_small = 10
cards.re_bomber_frenzy = 10
cards.re_boss_ambush = 10
cards.re_custom_1 = 10
cards.re_custom_10 = 10
cards.re_custom_11 = 10
cards.re_custom_12 = 10
cards.re_custom_13 = 20
cards.re_custom_14 = 10
cards.re_custom_15 = 10
cards.re_custom_16 = 10
cards.re_custom_17 = 7
cards.re_custom_18 = 10
cards.re_custom_19 = 10
cards.re_custom_2 = 10
cards.re_custom_20 = 10
cards.re_custom_21 = 10
cards.re_custom_22 = 10
cards.re_custom_23 = 10
cards.re_custom_24 = 12
cards.re_custom_25 = 10
cards.re_custom_26 = 10
cards.re_custom_27 = 10
cards.re_custom_28 = 10
cards.re_custom_29 = 10
cards.re_custom_3 = 10
cards.re_custom_30 = 10
cards.re_custom_31 = 10
cards.re_custom_32 = 10
cards.re_custom_33 = 10
cards.re_custom_34 = 10
cards.re_custom_35 = 10
cards.re_custom_36 = 10
cards.re_custom_37 = 10
cards.re_custom_38 = 10
cards.re_custom_39 = 10
cards.re_custom_4 = 10
cards.re_custom_40 = 10
cards.re_custom_41 = 10
cards.re_custom_42 = 10
cards.re_custom_43 = 10
cards.re_custom_44 = 10
cards.re_custom_45 = 10
cards.re_custom_46 = 10
cards.re_custom_47 = 10
cards.re_custom_48 = 10
cards.re_custom_49 = 10
cards.re_custom_5 = 1
cards.re_custom_50 = 10
cards.re_custom_51 = 10
cards.re_custom_52 = 7
cards.re_custom_53 = 12
cards.re_custom_54 = 10
cards.re_custom_55 = 12
cards.re_custom_56 = 15
cards.re_custom_57 = 10
cards.re_custom_58 = 10
cards.re_custom_59 = 10
cards.re_custom_6 = 10
cards.re_custom_60 = 10
cards.re_custom_61 = 10
cards.re_custom_62 = 10
cards.re_custom_63 = 10
cards.re_custom_64 = 10
cards.re_custom_65 = 10
cards.re_custom_66 = 10
cards.re_custom_67 = 10
cards.re_custom_68 = 10
cards.re_custom_69 = 10
cards.re_custom_7 = 10
cards.re_custom_70 = 10
cards.re_custom_71 = 10
cards.re_custom_72 = 10
cards.re_custom_73 = 10
cards.re_custom_74 = 10
cards.re_custom_75 = 10
cards.re_custom_76 = 10
cards.re_custom_77 = 10
cards.re_custom_78 = 10
cards.re_custom_79 = 10
cards.re_custom_8 = 10
cards.re_custom_80 = 10
cards.re_custom_81 = 10
cards.re_custom_82 = 10
cards.re_custom_83 = 10
cards.re_custom_84 = 10
cards.re_custom_85 = 10
cards.re_custom_86 = 10
cards.re_custom_87 = 10
cards.re_custom_88 = 10
cards.re_custom_9 = 10
cards.re_elite_squad = 10
cards.re_grenade_legion = 10
cards.re_hound_frenzy = 20
cards.re_ogryn_brutes = 10
cards.re_sniper_elite = 30
cards.re_special_pack = 10
cards.re_wave_huge = 10
cards.re_wave_large = 10
cards.re_wave_medium = 10
cards.re_wave_small = 5
cards.rf_bomber_frenzy = 60
cards.rf_boss_ambush = 60
cards.rf_custom_1 = 60
cards.rf_custom_10 = 60
cards.rf_custom_11 = 60
cards.rf_custom_12 = 60
cards.rf_custom_13 = 20
cards.rf_custom_14 = 60
cards.rf_custom_15 = 60
cards.rf_custom_16 = 60
cards.rf_custom_17 = 35
cards.rf_custom_18 = 60
cards.rf_custom_19 = 60
cards.rf_custom_2 = 60
cards.rf_custom_20 = 60
cards.rf_custom_21 = 60
cards.rf_custom_22 = 60
cards.rf_custom_23 = 60
cards.rf_custom_24 = 60
cards.rf_custom_25 = 60
cards.rf_custom_26 = 60
cards.rf_custom_27 = 60
cards.rf_custom_28 = 60
cards.rf_custom_29 = 60
cards.rf_custom_3 = 60
cards.rf_custom_30 = 60
cards.rf_custom_31 = 60
cards.rf_custom_32 = 60
cards.rf_custom_33 = 60
cards.rf_custom_34 = 60
cards.rf_custom_35 = 60
cards.rf_custom_36 = 60
cards.rf_custom_37 = 60
cards.rf_custom_38 = 60
cards.rf_custom_39 = 60
cards.rf_custom_4 = 60
cards.rf_custom_40 = 60
cards.rf_custom_41 = 60
cards.rf_custom_42 = 60
cards.rf_custom_43 = 60
cards.rf_custom_44 = 60
cards.rf_custom_45 = 60
cards.rf_custom_46 = 60
cards.rf_custom_47 = 60
cards.rf_custom_48 = 60
cards.rf_custom_49 = 60
cards.rf_custom_5 = 1
cards.rf_custom_50 = 60
cards.rf_custom_51 = 60
cards.rf_custom_52 = 21
cards.rf_custom_53 = 60
cards.rf_custom_54 = 60
cards.rf_custom_55 = 48
cards.rf_custom_56 = 30
cards.rf_custom_57 = 60
cards.rf_custom_58 = 60
cards.rf_custom_59 = 60
cards.rf_custom_6 = 60
cards.rf_custom_60 = 60
cards.rf_custom_61 = 60
cards.rf_custom_62 = 20
cards.rf_custom_63 = 60
cards.rf_custom_64 = 60
cards.rf_custom_65 = 60
cards.rf_custom_66 = 60
cards.rf_custom_67 = 60
cards.rf_custom_68 = 60
cards.rf_custom_69 = 60
cards.rf_custom_7 = 60
cards.rf_custom_70 = 60
cards.rf_custom_71 = 60
cards.rf_custom_72 = 60
cards.rf_custom_73 = 60
cards.rf_custom_74 = 60
cards.rf_custom_75 = 60
cards.rf_custom_76 = 60
cards.rf_custom_77 = 60
cards.rf_custom_78 = 60
cards.rf_custom_79 = 60
cards.rf_custom_8 = 60
cards.rf_custom_80 = 60
cards.rf_custom_81 = 60
cards.rf_custom_82 = 60
cards.rf_custom_83 = 60
cards.rf_custom_84 = 60
cards.rf_custom_85 = 60
cards.rf_custom_86 = 60
cards.rf_custom_87 = 60
cards.rf_custom_88 = 60
cards.rf_custom_9 = 60
cards.rf_elite_squad = 30
cards.rf_grenade_legion = 30
cards.rf_hound_frenzy = 40
cards.rf_ogryn_brutes = 60
cards.rf_sniper_elite = 30
cards.rf_special_pack = 20
cards.rf_wave_huge = 30
cards.rf_wave_large = 60
cards.rf_wave_medium = 60
cards.rf_wave_small = 20
cards.rk_bomber_frenzy = true
cards.rk_boss_ambush = false
cards.rk_custom_1 = true
cards.rk_custom_10 = true
cards.rk_custom_11 = true
cards.rk_custom_12 = true
cards.rk_custom_13 = true
cards.rk_custom_14 = true
cards.rk_custom_15 = true
cards.rk_custom_16 = true
cards.rk_custom_17 = true
cards.rk_custom_18 = true
cards.rk_custom_19 = true
cards.rk_custom_2 = true
cards.rk_custom_20 = true
cards.rk_custom_21 = true
cards.rk_custom_22 = true
cards.rk_custom_23 = true
cards.rk_custom_24 = true
cards.rk_custom_25 = true
cards.rk_custom_26 = true
cards.rk_custom_27 = true
cards.rk_custom_28 = true
cards.rk_custom_29 = true
cards.rk_custom_3 = true
cards.rk_custom_30 = true
cards.rk_custom_31 = true
cards.rk_custom_32 = true
cards.rk_custom_33 = true
cards.rk_custom_34 = true
cards.rk_custom_35 = true
cards.rk_custom_36 = true
cards.rk_custom_37 = true
cards.rk_custom_38 = true
cards.rk_custom_39 = true
cards.rk_custom_4 = true
cards.rk_custom_40 = true
cards.rk_custom_41 = true
cards.rk_custom_42 = true
cards.rk_custom_43 = true
cards.rk_custom_44 = true
cards.rk_custom_45 = true
cards.rk_custom_46 = true
cards.rk_custom_47 = true
cards.rk_custom_48 = true
cards.rk_custom_49 = true
cards.rk_custom_5 = true
cards.rk_custom_50 = true
cards.rk_custom_51 = true
cards.rk_custom_52 = true
cards.rk_custom_53 = true
cards.rk_custom_54 = true
cards.rk_custom_55 = true
cards.rk_custom_56 = true
cards.rk_custom_57 = true
cards.rk_custom_58 = true
cards.rk_custom_59 = true
cards.rk_custom_6 = true
cards.rk_custom_60 = true
cards.rk_custom_61 = true
cards.rk_custom_62 = true
cards.rk_custom_63 = true
cards.rk_custom_64 = true
cards.rk_custom_65 = true
cards.rk_custom_66 = true
cards.rk_custom_67 = true
cards.rk_custom_68 = true
cards.rk_custom_69 = true
cards.rk_custom_7 = true
cards.rk_custom_70 = true
cards.rk_custom_71 = true
cards.rk_custom_72 = true
cards.rk_custom_73 = true
cards.rk_custom_74 = true
cards.rk_custom_75 = true
cards.rk_custom_76 = true
cards.rk_custom_77 = true
cards.rk_custom_78 = true
cards.rk_custom_79 = true
cards.rk_custom_8 = true
cards.rk_custom_80 = true
cards.rk_custom_81 = true
cards.rk_custom_82 = true
cards.rk_custom_83 = true
cards.rk_custom_84 = true
cards.rk_custom_85 = true
cards.rk_custom_86 = true
cards.rk_custom_87 = true
cards.rk_custom_88 = true
cards.rk_custom_9 = true
cards.rk_elite_squad = true
cards.rk_grenade_legion = true
cards.rk_hound_frenzy = true
cards.rk_ogryn_brutes = true
cards.rk_sniper_elite = true
cards.rk_special_pack = true
cards.rk_wave_huge = true
cards.rk_wave_large = true
cards.rk_wave_medium = true
cards.rk_wave_small = false
cards.snd_bomber_frenzy = ""
cards.snd_boss_ambush = ""
cards.snd_custom_1 = "loc_enemy_daemonhost_a__mantra_2_09"
cards.snd_custom_10 = ""
cards.snd_custom_11 = ""
cards.snd_custom_12 = "loc_enemy_plasma_gunner_a__shooting_08"
cards.snd_custom_13 = "loc_enemy_traitor_scout_shocktrooper_a__take_position_01"
cards.snd_custom_14 = ""
cards.snd_custom_15 = ""
cards.snd_custom_16 = ""
cards.snd_custom_17 = "loc_enemy_captain_spiritual_b__long_death_01"
cards.snd_custom_18 = "loc_adamant_female_b__smart_tag_vo_enemy_netgunner_01"
cards.snd_custom_19 = ""
cards.snd_custom_2 = ""
cards.snd_custom_20 = "loc_captain_twin_male_a__taunt_a_01"
cards.snd_custom_21 = "loc_zealot_female_c__heard_enemy_chaos_spawn_01;wwise/events/minions/play_chaos_spawn_vce_4_attack_combo"
cards.snd_custom_22 = "wwise/events/minions/play_enemy_daemonhost_alert_scream"
cards.snd_custom_23 = "loc_psyker_female_b__com_wheel_vo_for_the_emperor_01"
cards.snd_custom_24 = "wwise/events/minions/play_minion_expeditions_horde_signal_3d_huge"
cards.snd_custom_25 = "loc_enemy_captain_spiritual_b__long_death_01"
cards.snd_custom_26 = ""
cards.snd_custom_27 = ""
cards.snd_custom_28 = "loc_adamant_male_c__heard_enemy_plague_ogryn_05"
cards.snd_custom_29 = "loc_adamant_male_c__seen_enemy_beast_of_nurgle_05"
cards.snd_custom_3 = "loc_captain_twin_female_a__mission_twins_cutscene_a_01"
cards.snd_custom_30 = ""
cards.snd_custom_31 = ""
cards.snd_custom_32 = ""
cards.snd_custom_33 = "loc_enemy_chaos_ogryn_heavy_gunner_a__shooting_02"
cards.snd_custom_34 = ""
cards.snd_custom_35 = ""
cards.snd_custom_36 = "loc_ogryn_a__com_wheel_vo_for_the_emperor_01"
cards.snd_custom_37 = "loc_enemy_traitor_netgunner_a__throwing_net_07"
cards.snd_custom_38 = ""
cards.snd_custom_39 = "loc_ogryn_a__smart_tag_vo_pickup_medical_crate_01"
cards.snd_custom_4 = ""
cards.snd_custom_40 = "loc_enemy_chaos_ogryn_armoured_executor_a__assault_10"
cards.snd_custom_41 = ""
cards.snd_custom_42 = ""
cards.snd_custom_43 = "loc_enemy_chaos_armored_infected_male_c__combat_idle_20"
cards.snd_custom_44 = "loc_zealot_male_c__seen_enemy_beast_of_nurgle_01"
cards.snd_custom_45 = ""
cards.snd_custom_46 = ""
cards.snd_custom_47 = ""
cards.snd_custom_48 = "loc_enemy_hound_master_a__spawn_a_01"
cards.snd_custom_49 = ""
cards.snd_custom_5 = ""
cards.snd_custom_50 = ""
cards.snd_custom_51 = "loc_enemy_hound_master_a__hound_attack_a_07"
cards.snd_custom_52 = ""
cards.snd_custom_53 = ""
cards.snd_custom_54 = ""
cards.snd_custom_55 = "loc_enemy_daemonhost_a__mantra_1_09"
cards.snd_custom_56 = ""
cards.snd_custom_57 = "loc_enemy_traitor_enforcer_executor_a__special_attack_08"
cards.snd_custom_58 = ""
cards.snd_custom_59 = ""
cards.snd_custom_6 = "loc_ogryn_b__seen_enemy_poxwalker_bomber_01"
cards.snd_custom_60 = ""
cards.snd_custom_61 = ""
cards.snd_custom_62 = ""
cards.snd_custom_63 = ""
cards.snd_custom_64 = "loc_captain_twin_female_a__cult_hurt_player_a_01"
cards.snd_custom_65 = "loc_enemy_chaos_armored_infected_male_a__attack_04"
cards.snd_custom_66 = ""
cards.snd_custom_67 = ""
cards.snd_custom_68 = "loc_ogryn_a__smart_tag_stimm_health_a_01"
cards.snd_custom_69 = "loc_adamant_female_a__found_ammo_veteran_low_on_ammo_01"
cards.snd_custom_7 = "loc_adamant_male_a__seen_enemy_mutant_charger_05"
cards.snd_custom_70 = ""
cards.snd_custom_71 = ""
cards.snd_custom_72 = "loc_enemy_chaos_ogryn_armoured_executor_a__assault_05"
cards.snd_custom_73 = ""
cards.snd_custom_74 = "loc_captain_twin_female_a__cult_downed_player_a_01"
cards.snd_custom_75 = ""
cards.snd_custom_76 = "loc_enemy_cultist_berzerker_b__assault_12;loc_enemy_cultist_berzerker_b__assault_16"
cards.snd_custom_77 = ""
cards.snd_custom_78 = ""
cards.snd_custom_79 = ""
cards.snd_custom_8 = "loc_ogryn_b__heard_enemy_houndmaster_01"
cards.snd_custom_80 = ""
cards.snd_custom_81 = ""
cards.snd_custom_82 = ""
cards.snd_custom_83 = ""
cards.snd_custom_84 = ""
cards.snd_custom_85 = ""
cards.snd_custom_86 = ""
cards.snd_custom_87 = ""
cards.snd_custom_88 = ""
cards.snd_custom_9 = "loc_psyker_male_a__heard_horde_vector_01"
cards.snd_elite_squad = "loc_enemy_cultist_berzerker_b__assault_12"
cards.snd_grenade_legion = ""
cards.snd_hound_frenzy = ""
cards.snd_ogryn_brutes = ""
cards.snd_sniper_elite = ""
cards.snd_special_pack = ""
cards.snd_wave_huge = ""
cards.snd_wave_large = ""
cards.snd_wave_medium = ""
cards.snd_wave_small = ""
cards.sp_bomber_frenzy = 3
cards.sp_boss_ambush = 3
cards.sp_custom_1 = 3
cards.sp_custom_10 = 3
cards.sp_custom_11 = 3
cards.sp_custom_12 = 5
cards.sp_custom_13 = 3
cards.sp_custom_14 = 5
cards.sp_custom_15 = 3
cards.sp_custom_16 = 5
cards.sp_custom_17 = 20
cards.sp_custom_18 = 3
cards.sp_custom_19 = 3
cards.sp_custom_2 = 3
cards.sp_custom_20 = 3
cards.sp_custom_21 = 3
cards.sp_custom_22 = 3
cards.sp_custom_23 = 3
cards.sp_custom_24 = 3
cards.sp_custom_25 = 3
cards.sp_custom_26 = 3
cards.sp_custom_27 = 3
cards.sp_custom_28 = 3
cards.sp_custom_29 = 3
cards.sp_custom_3 = 3
cards.sp_custom_30 = 3
cards.sp_custom_31 = 10
cards.sp_custom_32 = 3
cards.sp_custom_33 = 3
cards.sp_custom_34 = 3
cards.sp_custom_35 = 3
cards.sp_custom_36 = 3
cards.sp_custom_37 = 3
cards.sp_custom_38 = 3
cards.sp_custom_39 = 3
cards.sp_custom_4 = 3
cards.sp_custom_40 = 3
cards.sp_custom_41 = 3
cards.sp_custom_42 = 3
cards.sp_custom_43 = 3
cards.sp_custom_44 = 3
cards.sp_custom_45 = 3
cards.sp_custom_46 = 3
cards.sp_custom_47 = 3
cards.sp_custom_48 = 3
cards.sp_custom_49 = 3
cards.sp_custom_5 = 5
cards.sp_custom_50 = 3
cards.sp_custom_51 = 3
cards.sp_custom_52 = 5
cards.sp_custom_53 = 3
cards.sp_custom_54 = 10
cards.sp_custom_55 = 3
cards.sp_custom_56 = 3
cards.sp_custom_57 = 3
cards.sp_custom_58 = 40
cards.sp_custom_59 = 3
cards.sp_custom_6 = 100
cards.sp_custom_60 = 3
cards.sp_custom_61 = 3
cards.sp_custom_62 = 15
cards.sp_custom_63 = 3
cards.sp_custom_64 = 3
cards.sp_custom_65 = 3
cards.sp_custom_66 = 3
cards.sp_custom_67 = 3
cards.sp_custom_68 = 3
cards.sp_custom_69 = 3
cards.sp_custom_7 = 3
cards.sp_custom_70 = 3
cards.sp_custom_71 = 3
cards.sp_custom_72 = 3
cards.sp_custom_73 = 3
cards.sp_custom_74 = 3
cards.sp_custom_75 = 3
cards.sp_custom_76 = 3
cards.sp_custom_77 = 3
cards.sp_custom_78 = 3
cards.sp_custom_79 = 3
cards.sp_custom_8 = 3
cards.sp_custom_80 = 3
cards.sp_custom_81 = 3
cards.sp_custom_82 = 3
cards.sp_custom_83 = 3
cards.sp_custom_84 = 3
cards.sp_custom_85 = 3
cards.sp_custom_86 = 3
cards.sp_custom_87 = 3
cards.sp_custom_88 = 3
cards.sp_custom_9 = 2
cards.sp_elite_squad = 1
cards.sp_grenade_legion = 50
cards.sp_hound_frenzy = 3
cards.sp_ogryn_brutes = 3
cards.sp_sniper_elite = 1
cards.sp_special_pack = 3
cards.sp_wave_huge = 30
cards.sp_wave_large = 5
cards.sp_wave_medium = 3
cards.sp_wave_small = 5
cards.su_bomber_frenzy = "brute"
cards.su_boss_ambush = "fateful"
cards.su_custom_1 = "warp"
cards.su_custom_10 = "murmur"
cards.su_custom_11 = "blight"
cards.su_custom_12 = "volley"
cards.su_custom_13 = "volley"
cards.su_custom_14 = "volley"
cards.su_custom_15 = "blight"
cards.su_custom_16 = "volley"
cards.su_custom_17 = "nightmare"
cards.su_custom_18 = "snare"
cards.su_custom_19 = "blight"
cards.su_custom_2 = "fateful"
cards.su_custom_20 = "murmur"
cards.su_custom_21 = "heresy"
cards.su_custom_22 = "nightmare"
cards.su_custom_23 = "miracle"
cards.su_custom_24 = "warp"
cards.su_custom_25 = "nightmare"
cards.su_custom_26 = "faith"
cards.su_custom_27 = "prayer"
cards.su_custom_28 = "heresy"
cards.su_custom_29 = "heresy"
cards.su_custom_3 = "murmur"
cards.su_custom_30 = "rage"
cards.su_custom_31 = "volley"
cards.su_custom_32 = "rage"
cards.su_custom_33 = "volley"
cards.su_custom_34 = "faith"
cards.su_custom_35 = "miracle"
cards.su_custom_36 = "grace"
cards.su_custom_37 = "snare"
cards.su_custom_38 = "grace"
cards.su_custom_39 = "prayer"
cards.su_custom_4 = "plague"
cards.su_custom_40 = "plague"
cards.su_custom_41 = "prayer"
cards.su_custom_42 = "grace"
cards.su_custom_43 = "plague"
cards.su_custom_44 = "fateful"
cards.su_custom_45 = "volley"
cards.su_custom_46 = "dream"
cards.su_custom_47 = "faith"
cards.su_custom_48 = "heresy"
cards.su_custom_49 = "faith"
cards.su_custom_5 = "murmur"
cards.su_custom_50 = "dream"
cards.su_custom_51 = "snare"
cards.su_custom_52 = "plague"
cards.su_custom_53 = "warp"
cards.su_custom_54 = "brute"
cards.su_custom_55 = "warp"
cards.su_custom_56 = "swarm"
cards.su_custom_57 = "plague"
cards.su_custom_58 = "snare"
cards.su_custom_59 = "swarm"
cards.su_custom_6 = "warp"
cards.su_custom_60 = "fateful"
cards.su_custom_61 = "fateful"
cards.su_custom_62 = "rage"
cards.su_custom_63 = "snare"
cards.su_custom_64 = "fateful"
cards.su_custom_65 = "swarm"
cards.su_custom_66 = "heresy"
cards.su_custom_67 = "grace"
cards.su_custom_68 = "grace"
cards.su_custom_69 = "prayer"
cards.su_custom_7 = "warp"
cards.su_custom_70 = "dream"
cards.su_custom_71 = "plague"
cards.su_custom_72 = "plague"
cards.su_custom_73 = "faith"
cards.su_custom_74 = "fateful"
cards.su_custom_75 = "brute"
cards.su_custom_76 = "nightmare"
cards.su_custom_77 = "plague"
cards.su_custom_78 = "plague"
cards.su_custom_79 = "plague"
cards.su_custom_8 = "fateful"
cards.su_custom_80 = "plague"
cards.su_custom_81 = "plague"
cards.su_custom_82 = "plague"
cards.su_custom_83 = "plague"
cards.su_custom_84 = "plague"
cards.su_custom_85 = "plague"
cards.su_custom_86 = "plague"
cards.su_custom_87 = "plague"
cards.su_custom_88 = "plague"
cards.su_custom_9 = "swarm"
cards.su_elite_squad = "rage"
cards.su_grenade_legion = "plague"
cards.su_hound_frenzy = "murmur"
cards.su_ogryn_brutes = "brute"
cards.su_sniper_elite = "volley"
cards.su_special_pack = "rage"
cards.su_wave_huge = "swarm"
cards.su_wave_large = "swarm"
cards.su_wave_medium = "swarm"
cards.su_wave_small = "fateful"
cards.th_bomber_frenzy = 5
cards.th_boss_ambush = 4
cards.th_custom_1 = 5
cards.th_custom_10 = 4
cards.th_custom_11 = 5
cards.th_custom_12 = 4
cards.th_custom_13 = 5
cards.th_custom_14 = 0
cards.th_custom_15 = 1
cards.th_custom_16 = 5
cards.th_custom_17 = 6
cards.th_custom_18 = 4
cards.th_custom_19 = 0
cards.th_custom_2 = 5
cards.th_custom_20 = 5
cards.th_custom_21 = 6
cards.th_custom_22 = 6
cards.th_custom_23 = 6
cards.th_custom_24 = 5
cards.th_custom_25 = 6
cards.th_custom_26 = 3
cards.th_custom_27 = 5
cards.th_custom_28 = 6
cards.th_custom_29 = 6
cards.th_custom_3 = 5
cards.th_custom_30 = 2
cards.th_custom_31 = 0
cards.th_custom_32 = 2
cards.th_custom_33 = 4
cards.th_custom_34 = 4
cards.th_custom_35 = 4
cards.th_custom_36 = 6
cards.th_custom_37 = 4
cards.th_custom_38 = 4
cards.th_custom_39 = 5
cards.th_custom_4 = 0
cards.th_custom_40 = 5
cards.th_custom_41 = 5
cards.th_custom_42 = 6
cards.th_custom_43 = 4
cards.th_custom_44 = 4
cards.th_custom_45 = 0
cards.th_custom_46 = 6
cards.th_custom_47 = 4
cards.th_custom_48 = 6
cards.th_custom_49 = 3
cards.th_custom_5 = 4
cards.th_custom_50 = 6
cards.th_custom_51 = 4
cards.th_custom_52 = 0
cards.th_custom_53 = 5
cards.th_custom_54 = 5
cards.th_custom_55 = 6
cards.th_custom_56 = 2
cards.th_custom_57 = 3
cards.th_custom_58 = 3
cards.th_custom_59 = 2
cards.th_custom_6 = 3
cards.th_custom_60 = 4
cards.th_custom_61 = 5
cards.th_custom_62 = 5
cards.th_custom_63 = 6
cards.th_custom_64 = 4
cards.th_custom_65 = 4
cards.th_custom_66 = 5
cards.th_custom_67 = 4
cards.th_custom_68 = 3
cards.th_custom_69 = 5
cards.th_custom_7 = 4
cards.th_custom_70 = 6
cards.th_custom_71 = 5
cards.th_custom_72 = 0
cards.th_custom_73 = 5
cards.th_custom_74 = 0
cards.th_custom_75 = 3
cards.th_custom_76 = 6
cards.th_custom_77 = 0
cards.th_custom_78 = 0
cards.th_custom_79 = 0
cards.th_custom_8 = 3
cards.th_custom_80 = 0
cards.th_custom_81 = 0
cards.th_custom_82 = 0
cards.th_custom_83 = 0
cards.th_custom_84 = 0
cards.th_custom_85 = 0
cards.th_custom_86 = 0
cards.th_custom_87 = 0
cards.th_custom_88 = 0
cards.th_custom_9 = 2
cards.th_elite_squad = 4
cards.th_grenade_legion = 0
cards.th_hound_frenzy = 4
cards.th_ogryn_brutes = 4
cards.th_sniper_elite = 3
cards.th_special_pack = 1
cards.th_wave_huge = 0
cards.th_wave_large = 4
cards.th_wave_medium = 2
cards.th_wave_small = 4
cards.wave_def_bomber_frenzy = "The Tower\t1 crusher[garden+toll+purple_stimm]{health=1000 size=120 speed=140 gap=50 cancel=15 boss=1}<applied_stimm!:FFFFFFFF>(name The Tower)(colour 453f3f)(twins chaos_ogryn_executor chaos_ogryn_executor 0000 1)"
cards.wave_def_boss_ambush = "The Devil\t2 plague ogryn|beast of nurgle|chaos spawn|packmaster"
cards.wave_def_custom_1 = "The Forbidden\t1 daemonhost[garden]{speed=120 gap=83 mass=10 dot=130 boss=1}(leaves 2)(name The Forbidden)(colour b050ff)"
cards.wave_def_custom_10 = "The Shade\t3 crusher{health=250 size=65 speed=135 gap=80 boss=1}<applied_stimm:B4565779>(name The Shade)(colour 57534f), 10 poxwalker{health=200 size=115 speed=140 mass=50 explosion=15}, 10 mutated poxwalker{health=200 size=115 speed=140 explosion=15}, 15 scab{health=200 size=115 speed=130 explosion=15}"
cards.wave_def_custom_11 = "The Glutton\t1 beast of nurgle{health=200 speed=150 gap=77}, 3 dreg vanguard[garden+corrupted]{health=250 speed=115 gap=87}"
cards.wave_def_custom_12 = "The Glass\t3 plasma gunner{health=80 size=115 speed=130 gap=80 fire=75 explosion=300 dot=300 damage=250 boss=1}<applied_stimm+outline!:FFFFFFFF>(name Glass Cannon)(colour d1e3bc)"
cards.wave_def_custom_13 = "The Salvo\t2 shocktrooper[garden+purple_stimm]{health=125 speed=110 gap=80 fire=50 burst=150}(twins renegade_shocktrooper renegade_shocktrooper 1010 2)@=, 2 dreg shocktrooper[garden+purple_stimm]{health=125 speed=110 gap=80 fire=50 burst=150}(twins renegade_shocktrooper renegade_shocktrooper 1010 2)@="
cards.wave_def_custom_14 = "The Vultures\t4 scab assault{health=150 size=80 speed=110 damage=200}<applied_stimm!:FF72FF35>"
cards.wave_def_custom_15 = "The Wretched\t25 dreg[corrupted+toughened]{speed=125 gap=80 mass=125}"
cards.wave_def_custom_16 = "The Firepower\t5 reaper[toll+toughened]{health=250 size=110 speed=125 fire=75}, 3 plasma gunner[enraged+toughened]{health=200 speed=125 fire=75}, 2 sniper{health=150 fire=75}, 2 shocktrooper[toughened]{health=150 fire=75}"
cards.wave_def_custom_17 = "The Festering Carnival\t3 mutant{health=200 speed=150 gap=50}<skin_warp:FF8000FF>@=, 3 burster{health=200 speed=135 damage=200}<skin_warp:FF8000FF>@=, 2 burster[enraged]{health=50 size=130 speed=50 damage=500}<applied_stimm:F8FF6900>, 1 tox flamer{gap=75}@="
cards.wave_def_custom_18 = "The Triad\t3 trapper[enraged]{health=600 size=105 speed=175 mass=250 explosion=50 dot=80 net=15 pause=10 boss=1}(name The Triad)"
cards.wave_def_custom_19 = "The Turning\t1 mutated poxwalker[corrupted]{health=1000 size=110 speed=125 gap=80}<skin_warp:FF8000FF>"
cards.wave_def_custom_2 = "The Fortress\t3 mauler{health=200 speed=110 gap=91 mass=150}, 1 bulwark[toll+purple_stimm]{health=250 size=110 speed=115 gap=77}, 1 bulwark[garden+enraged+purple_stimm]{health=250 speed=115 gap=77}, 5 dreg vanguard[bolstering]{health=200 speed=110 gap=91}, 5 scab vanguard[bolstering]{health=200 speed=110 gap=91}"
cards.wave_def_custom_20 = "The Ascendant\t1 dreg captain[garden+enraged]{health=250 speed=140 gap=50 burst=200 damage=300 boss=1}<applied_stimm+outline!:FFA68B93>(name The Ascendant)(colour b3b1af)"
cards.wave_def_custom_21 = "Wrath\t1 chaos spawn[enraged]{health=350 size=110 speed=140 gap=30 mass=50 explosion=150 dot=150 damage=150 cancel=30 combo=1 boss=1}<outline+outline!:B4FFC700>(name Wrath)(colour 850404)"
cards.wave_def_custom_22 = "The End\t1 daemonhost[garden]{health=80 gap=75 boss=1}<applied_stimm+outline!:FF9B00FF>(name The End)(colour b050ff), 1 daemonhost{health=80 gap=75 boss=1}(name The End)(colour b050ff)"
cards.wave_def_custom_23 = "Miracle\t"
cards.wave_def_custom_24 = "Time Rift\t1 chaos spawn|plague ogryn{health=30 size=85 speed=120 gap=50 mass=50 damage=130 cancel=25 combo=1 boss=1}<applied_stimm+outline!:FF4D59FF>(name Time Anomaly)(colour d18cc0)@="
cards.wave_def_custom_25 = "Darkness\t3 crusher[purple_stimm]{health=125 speed=115 gap=75 damage=150 cancel=25 boss=1}<skin_warp+outline!:37A000B8>(name Dark Crusher)(colour 3b3737)(twins chaos_ogryn_executor chaos_ogryn_executor 1010 3), 3 bulwark[purple_stimm]{health=150 size=105 damage=150}<skin_warp:FF8000FF>(twins chaos_ogryn_bulwark chaos_ogryn_bulwark 1010 3)"
cards.wave_def_custom_26 = "Sight\t"
cards.wave_def_custom_27 = "War Vial\t"
cards.wave_def_custom_28 = "Anger\t1 plague ogryn[enraged]{health=400 speed=110 gap=50 explosion=200 dot=200 damage=200 cancel=30 combo=1 boss=1}<applied_stimm+outline!:FF8B0000>(colour 661818)"
cards.wave_def_custom_29 = "Blasphemy\t1 beast of nurgle[enraged]{health=600 size=105 speed=140 gap=25 explosion=200 dot=200 damage=150 cancel=30 spray=40 boss=1}<applied_stimm:FFFFFF00>(name Blasphemy)(colour 690808)"
cards.wave_def_custom_3 = "The Brothers\t1 ranged twin{speed=125}, 1 melee twin{gap=80}"
cards.wave_def_custom_30 = "Bare-Chested\t1 rager[fire+purple_stimm]{health=170 speed=90 gap=80 mass=70 explosion=20 dot=80}<applied_stimm!:D6FF7100>(twins cultist_berzerker cultist_berzerker 0000 1), 2 rager[fire+purple_stimm]{health=200 speed=90 gap=80 mass=70 explosion=20 dot=80 damage=120}<applied_stimm!:FFFF7000>"
cards.wave_def_custom_31 = "Firing Line\t5 scab assault[purple_stimm]{health=130 size=120 speed=120 mass=120}, 5 rifleman[purple_stimm]{health=130 size=120 speed=110}, 5 gunner[purple_stimm]{health=130 size=120}, 4 shocktrooper[purple_stimm]{health=130 size=120 fire=80}, 2 plasma gunner[purple_stimm]{health=130 size=120}"
cards.wave_def_custom_32 = "The Burning Tide\t30 poxwalker[fire]{health=150 size=115 speed=115}"
cards.wave_def_custom_33 = "The Walking Turret\t1 reaper[enraged+toughened+parasite]{health=500 size=135 speed=150 mass=25 dot=150 damage=150 boss=1}<applied_stimm+outline!:CDFF3D60>(name The Turret)(colour e8e8e8)"
cards.wave_def_custom_34 = "The Bountiful Hand\t"
cards.wave_def_custom_35 = "The Second Dawn\t"
cards.wave_def_custom_36 = "Apotheosis\t"
cards.wave_def_custom_37 = "Warped Units\t2 trapper[enraged]{health=1000 size=110 speed=170 gap=25 net=60 pause=2 boss=1}<skin_warp!:FFFFFFFF>(name Warped Trapper)(colour 69041e)"
cards.wave_def_custom_38 = "Temperance\t"
cards.wave_def_custom_39 = "The Sanctuary\t"
cards.wave_def_custom_4 = "The Foul Iron\t2 crusher[bolstering+rotten]{health=150 speed=110 mass=200}, 3 mauler[bolstering+rotten]{health=150 speed=110 gap=87}, 4 scab rager[bolstering+rotten]{health=150 speed=110 gap=87 mass=50}"
cards.wave_def_custom_40 = "The Hollow Giants\t5 crusher[purple_stimm+rotten]{health=170 size=115 speed=90 gap=90 explosion=150 dot=150 cancel=20 boss=1}<applied_stimm!:FF48D362>(name Hollow Giant)(colour 477514)"
cards.wave_def_custom_41 = "The Armoury's Gift\t"
cards.wave_def_custom_42 = "Communion\t"
cards.wave_def_custom_43 = "Hollow Rage\t7 scab rager[bolstering+rotten]{health=120 size=105 speed=110 mass=50 damage=130 cancel=20}<skin_bruise:FF8000FF>"
cards.wave_def_custom_44 = "The Council\t1 plague ogryn{health=33 size=90 damage=150 boss=1}<skin_bruise!:FF8000FF>(name The Council Ogryn), 1 beast of nurgle{health=33 size=90 damage=150 boss=1}<skin_bruise!:FF8000FF>(name The Council Beast)(colour 9cb030), 1 chaos spawn{health=33 size=90 damage=150 boss=1}<skin_bruise!:FF8000FF>(name The Council Chaos)(colour e8e8e8)"
cards.wave_def_custom_45 = "The Dirty Dozen\t12 shocktrooper{health=70 size=95 damage=70}"
cards.wave_def_custom_46 = "Dream\t"
cards.wave_def_custom_47 = "Blessed Ordnance\t"
cards.wave_def_custom_48 = "Insanity\t1 packmaster[enraged]{health=200 speed=115 gap=50 mass=50 damage=150 cancel=30 combo=1 boss=1}<applied_stimm+outline!:FFFF0E00>(no dogs)(name Insanity)(colour 690808)"
cards.wave_def_custom_49 = "Elite Vision\t"
cards.wave_def_custom_5 = "The Reflection\t1 beast of nurgle|chaos spawn|melee twin|packmaster|plague ogryn|ranged twin{health=50 speed=110 boss=1}<applied_stimm+outline!:CEC5C3C3>(no dogs)(name The Mirror)(colour e8e8e8)@="
cards.wave_def_custom_50 = "Fever Dream\t"
cards.wave_def_custom_51 = "Warped Creatures\t2 armored hound[enraged]{health=1000 size=105 speed=160 gap=25 damage=200 cancel=50 pause=6 boss=1}<skin_warp+outline!:C9807F3A>(name Warped Hound)(colour 9e9a1e)"
cards.wave_def_custom_52 = "Nurglings\t1 beast of nurgle{health=15 size=50 speed=130 spray=100 boss=1}<slot_stimm+outline!:CB94932E>(name Nurglings)(colour 667513)@="
cards.wave_def_custom_53 = "Minor Warp Rift\t1 daemonhost[purple_stimm]{health=15 size=80 boss=1}(name Weakened Daemonhost)(colour 4890ff)(twins chaos_poxwalker_bomber default 0000 1)@="
cards.wave_def_custom_54 = "Frenzied Armour\t4 mauler[toll+purple_stimm]{health=500 size=125 speed=125 gap=65 mass=150 damage=150 cancel=33 combo=1 boss=1}<applied_stimm+outline!:D2FF2500>(name Frenzied Mauler)(colour 940a0a)(twins renegade_executor default 0000 1)"
cards.wave_def_custom_55 = "Warp Assault\t1 daemonhost{health=15 size=85 cancel=20 combo=1}<skin_warp:FFA900D7>@="
cards.wave_def_custom_56 = "Trampled Soul\t50 poxwalker{health=150 speed=130 explosion=75}@="
cards.wave_def_custom_57 = "Hollow Frontline\t7 mauler[purple_stimm+rotten]{health=150 size=110 speed=90 gap=75 mass=50 damage=130 boss=1}<applied_stimm!:FF6DA26F>(name Hollow Mauler)(colour 476b23)"
cards.wave_def_custom_58 = "Special Deliverance\t3 flamer, 3 hound, 3 mutant, 3 burster, 3 bomber, 3 trapper, 3 sniper"
cards.wave_def_custom_59 = "Shield Wall\t5 scab vanguard[bolstering], 5 dreg vanguard[bolstering]"
cards.wave_def_custom_6 = "The Calamity\t1 burster[enraged]{health=700 size=175 speed=40 damage=500 boss=1}<outline+outline!:FFFF9800>(name The Calamity)(colour 8f1b6d)"
cards.wave_def_custom_60 = "The Captains\t2 dreg captain{health=50 speed=130 gap=50}(no shield), 2 captain{health=50 speed=130 gap=50}(no shield)"
cards.wave_def_custom_61 = "Minefield\t5 ranged twin{health=20}(no shield)"
cards.wave_def_custom_62 = "Engulfed in flames\t5 flamer[bolstering+fire]{health=200 speed=125}<skin_burnt:FF8000FF>@=, 5 bomber[bolstering+fire]{health=200 speed=125}<skin_burnt:FF8000FF>@=, 3 burster@="
cards.wave_def_custom_63 = "Chain Reaction\t1 burster[purple_stimm]{health=200 size=175 speed=75 damage=200 boss=1}(name Matryoshka)(colour ff5aa8)(twins chaos_poxwalker_bomber chaos_poxwalker_bomber 1111 4)"
cards.wave_def_custom_64 = "The Forgotten Frontline\t3 melee twin{health=20 speed=110 damage=75}(no shield)"
cards.wave_def_custom_65 = "The Legion Within\t2 armored infected[purple_stimm]{health=1000 size=140 speed=150 gap=50 explosion=25 dot=25 boss=1}<applied_stimm!:FFFFFFFF>(name The Legion Within)(colour e8e8e8)(twins chaos_armored_infected chaos_armored_infected 1010 5)"
cards.wave_def_custom_66 = "The Trojan Horse\t1 mutant[purple_stimm]{health=500 size=130 speed=130 damage=250 boss=1}<applied_stimm!:FF684428>(name Trojan Horse)(colour b55543)(twins chaos_plague_ogryn chaos_beast_of_nurgle 0000 1)"
cards.wave_def_custom_67 = "The Endurance\t"
cards.wave_def_custom_68 = "Sanctioned Dose\t"
cards.wave_def_custom_69 = "The Blessed Shell\t"
cards.wave_def_custom_7 = "The Chasers\t2 mutant[enraged]{health=750 size=115 speed=200 gap=25 dot=50 damage=250 boss=1}(name The Chaser)(colour 5ec850)"
cards.wave_def_custom_70 = "Blessed Magazine\t"
cards.wave_def_custom_71 = "The Undying\t1 tox bomber[purple_stimm]{health=200 size=125 speed=125 gap=25 explosion=50 dot=50 boss=1}<applied_stimm!:CD9AFF00>(name The Undying Plague)(colour 9cb030)(twins cultist_grenadier none 1000 5)"
cards.wave_def_custom_72 = "The Unburied\t1 mauler[purple_stimm+rotten]{health=200 size=120 speed=105 gap=75 damage=125 boss=1}<applied_stimm!:FF00FF00>(name The Unburied)(colour 9cb030)(twins renegade_executor none 1100 5)"
cards.wave_def_custom_73 = "Perfect Sight\t"
cards.wave_def_custom_74 = "The Only Child\t1 melee twin{health=130 speed=110 gap=75 damage=130 cancel=40 combo=1 boss=1}<applied_stimm!:FFFFFFFF>(no shield)(name The Only Child)(colour e8e8e8)"
cards.wave_def_custom_75 = "The Evolved\t1 scab vanguard[enraged+purple_stimm]{health=1000 size=115 speed=125 gap=50 boss=1}<applied_stimm!:FFFFFFFF>(name The Evolved)(colour e8e8e8)(twins chaos_ogryn_bulwark chaos_ogryn_bulwark 1010 2)"
cards.wave_def_custom_76 = "Endless Rage\t2 rager[purple_stimm]{size=105 speed=95 explosion=80 damage=120 cancel=20 combo=1 boss=1}<skin_warp+outline!:FFA3A081>(name Ira)(colour 706965)(twins cultist_berzerker cultist_berzerker 1111 4)"
cards.wave_def_custom_77 = ""
cards.wave_def_custom_78 = ""
cards.wave_def_custom_79 = ""
cards.wave_def_custom_8 = "The Pursuer\t1 packmaster{health=40 size=90 speed=170 gap=50 cancel=25 combo=1 boss=1}(name The Pursuer)(colour e8c040)"
cards.wave_def_custom_80 = ""
cards.wave_def_custom_81 = ""
cards.wave_def_custom_82 = ""
cards.wave_def_custom_83 = ""
cards.wave_def_custom_84 = ""
cards.wave_def_custom_85 = ""
cards.wave_def_custom_86 = ""
cards.wave_def_custom_87 = ""
cards.wave_def_custom_88 = ""
cards.wave_def_custom_9 = "The Infested\t35 mutated poxwalker{health=400 gap=80 mass=20}, 1 dreg vanguard[garden]{health=300 size=110 gap=91 mass=300}, 5 dreg{health=250 mass=20}"
cards.wave_def_elite_squad = "The Chariot\t7 rager[toll+purple_stimm]{health=200 size=115 speed=125}"
cards.wave_def_grenade_legion = "The Fumes\t1 tox bomber{speed=150 gap=83}@="
cards.wave_def_hound_frenzy = "The Hunt\t2 armored hound[enraged]{health=500 speed=125 gap=50 boss=1}(name Gorehound)(colour 8f1f36)@="
cards.wave_def_ogryn_brutes = "The Brutes\t2 crusher[purple_stimm]{health=200}, 2 bulwark[purple_stimm]{health=200}, 2 reaper[purple_stimm]{health=200 fire=125}"
cards.wave_def_sniper_elite = "The Sharpshooters\t1 sniper[garden+purple_stimm]{health=300 size=130 speed=150 fire=25 damage=500}(twins renegade_sniper none 0100 1)@1, 1 sniper[garden]{health=300 size=125 speed=130 gap=33 fire=25 damage=500}@1"
cards.wave_def_special_pack = "The Scorch\t1 tox flamer[toughened]{health=200 speed=130 gap=83}@=, 1 bomber[toughened]{health=200 speed=130}@="
cards.wave_def_wave_huge = "oh shit\t5 shocktrooper, 10 crusher, 10 mauler, 1 plague ogryn[enraged], 1 chaos spawn[toll], 10 scab rager"
cards.wave_def_wave_large = "The Final Pilgrimage\t4 scab[purple_stimm]{health=500 size=105 speed=115 gap=91 mass=300 explosion=60 dot=60}, 1 melee twin{health=125 size=105 speed=110 gap=77 dot=150 boss=1}(no shield)(name The Pilgrim Twin)(colour 3cbcb0), 1 scab[garden+purple_stimm]{health=400 size=110 speed=115 gap=91 mass=250}"
cards.wave_def_wave_medium = "The Pilgrims\t30 poxwalker{health=750 size=110 speed=135 mass=50 explosion=30 dot=30}<applied_stimm:FF7D0000>"
cards.wave_def_wave_small = "The Wheel\t3 armored hound|armored infected|beast of nurgle|bomber|bulwark|burster|captain|chaos spawn|crusher|daemonhost|dreg|dreg assault|dreg captain|dreg gunner|dreg shocktrooper|dreg vanguard|flamer|gunner|hound|lesser mutated poxwalker|mauler|melee twin|mutant|mutated poxwalker|newly infected|packmaster|plague ogryn|plasma gunner|poxwalker|radio operator|rager|ranged twin|reaper|rifleman|scab|scab assault|scab rager|scab vanguard|shocktrooper|sniper|tox bomber|tox flamer|trapper<slot_stimm:D68000FF>"
cards.wh_bomber_frenzy = "Unwavering, unbreakable, unstoppable."
cards.wh_boss_ambush = "Something big is listening."
cards.wh_custom_1 = "All hope is lost."
cards.wh_custom_10 = "The killing blow cometh unseen."
cards.wh_custom_11 = "Its hunger knoweth no end."
cards.wh_custom_12 = "Death cometh swift, for both."
cards.wh_custom_13 = "Stand close, and perish."
cards.wh_custom_14 = "They feast upon the unwary."
cards.wh_custom_15 = "Frail bodies, foul purpose."
cards.wh_custom_16 = "The barrage shall know no end."
cards.wh_custom_17 = "Nurgle's fairground never closes."
cards.wh_custom_18 = "Escape shall not be granted."
cards.wh_custom_19 = "One shall turn the tide."
cards.wh_custom_2 = "The bastion marches."
cards.wh_custom_20 = "Where he walks, discipline follows."
cards.wh_custom_21 = "Total annihilation."
cards.wh_custom_22 = "No faith shall save thee."
cards.wh_custom_23 = ""
cards.wh_custom_24 = "Time is wounded. Something is leaking."
cards.wh_custom_25 = "It never ends."
cards.wh_custom_26 = "Nothing hides from the faithful."
cards.wh_custom_27 = ""
cards.wh_custom_28 = "Every insult you ever earned."
cards.wh_custom_29 = "A prayer inverted, and given teeth."
cards.wh_custom_3 = "Don't they look desperate, brother?"
cards.wh_custom_30 = "They didn't come here to live."
cards.wh_custom_31 = "Grandfather blessed their aim."
cards.wh_custom_32 = "Don't let them hug you."
cards.wh_custom_33 = ""
cards.wh_custom_34 = "Belief fills what battle emptied."
cards.wh_custom_35 = "The trumpet sounds. The fallen stand"
cards.wh_custom_36 = "Be a god for a single breath."
cards.wh_custom_37 = "Patience is a hunter's finest weapon."
cards.wh_custom_38 = "Break the bread. Share the breath"
cards.wh_custom_39 = "A brief mercy in the Emperor's war."
cards.wh_custom_4 = "Their armor rotteth, yet endureth."
cards.wh_custom_40 = "Death is only the first birth."
cards.wh_custom_41 = "Every round is a prayer answered."
cards.wh_custom_42 = "In unity, there is no weakness."
cards.wh_custom_43 = "Stripped of plate. Not of purpose."
cards.wh_custom_44 = "Three verdicts. One sentence."
cards.wh_custom_45 = "Spent shells fall like heavy rain."
cards.wh_custom_46 = ""
cards.wh_custom_47 = "Bless the pin, bless the hand."
cards.wh_custom_48 = "No one is left behind. Not down here."
cards.wh_custom_49 = ""
cards.wh_custom_5 = "Two shall answer where one was called."
cards.wh_custom_50 = "Fight through your demons and ascend."
cards.wh_custom_51 = "It wasn't hesitation. It was patience."
cards.wh_custom_52 = ""
cards.wh_custom_53 = "Pieces of it crawled out."
cards.wh_custom_54 = ""
cards.wh_custom_55 = "Someone stop the voices."
cards.wh_custom_56 = ""
cards.wh_custom_57 = ""
cards.wh_custom_58 = ""
cards.wh_custom_59 = "Cheap flesh behind good iron."
cards.wh_custom_6 = "The earth shall soon tremble."
cards.wh_custom_60 = "A ship with many masters sinks fast."
cards.wh_custom_61 = "Step into the open. We dare you."
cards.wh_custom_62 = ""
cards.wh_custom_63 = "The Corpse Explodes Anew"
cards.wh_custom_64 = "The cursed Triplets."
cards.wh_custom_65 = "Every end is a birth."
cards.wh_custom_66 = "Something feels off."
cards.wh_custom_67 = "Pain is only the Emperor testing you."
cards.wh_custom_68 = "Cleanse flesh. Renew the fight."
cards.wh_custom_69 = ""
cards.wh_custom_7 = "He shall hunt thee unto death."
cards.wh_custom_70 = "Ammunition is faith made manifest."
cards.wh_custom_71 = "Nurgle refuses to let it rest."
cards.wh_custom_72 = "The grave rejects it"
cards.wh_custom_73 = "Blind faith."
cards.wh_custom_74 = "Two Fates Haunt One Soul."
cards.wh_custom_75 = "Rumor has it there is a secret."
cards.wh_custom_76 = "The Eternal Rage lingers."
cards.wh_custom_77 = ""
cards.wh_custom_78 = ""
cards.wh_custom_79 = ""
cards.wh_custom_8 = "The hunt beginneth."
cards.wh_custom_80 = ""
cards.wh_custom_81 = ""
cards.wh_custom_82 = ""
cards.wh_custom_83 = ""
cards.wh_custom_84 = ""
cards.wh_custom_85 = ""
cards.wh_custom_86 = ""
cards.wh_custom_87 = ""
cards.wh_custom_88 = ""
cards.wh_custom_9 = "The putrid masses draw near."
cards.wh_elite_squad = "The mad charge. The weak flee."
cards.wh_grenade_legion = "Breathe deep, and perish."
cards.wh_hound_frenzy = "When dusk falls, the hunt begins."
cards.wh_ogryn_brutes = "Might before mind."
cards.wh_sniper_elite = "Swift, Foul, Unerring."
cards.wh_special_pack = "The flames shall cleanse all."
cards.wh_wave_huge = "There are always more."
cards.wh_wave_large = "Their faith faileth not."
cards.wh_wave_medium = "Faith carries them where flesh cannot."
cards.wh_wave_small = "The Wheel Turneth. Pray He Favors Thee."
UserDefaults.cards = cards

-- the settings of one card (its key: "wave_small", "custom_7"): { setting = value }, built once (again only if `cards` is replaced)
local by_card, built_from = nil, nil

UserDefaults.card = function (key)
	if built_from ~= UserDefaults.cards then
		by_card, built_from = {}, UserDefaults.cards

		for setting, value in pairs(UserDefaults.cards) do
			for _, prefix in ipairs(UserDefaults.CARD_PREFIXES) do
				if setting:sub(1, #prefix) == prefix then
					local card = setting:sub(#prefix + 1)

					by_card[card] = by_card[card] or {}
					by_card[card][setting] = value

					break
				end
			end
		end
	end

	return by_card[key] or {}
end

return UserDefaults
