-- NOTE: DMF runs every localized string through string.format. A bare "%" is an
-- error ("invalid option '%' to 'format'"); write "%%" only in strings that are
-- always localized with arguments, otherwise avoid the character (use "percent").
return {
	btn_appearance = { en = "Enemy colour experiments" },
	view_desc_appearance = { en = "Enemy colour experiments: %s" },
	appearance_strength_info = { en = "A = tint strength. Swatch previews the input colour; the game result depends on the method and enemy materials." },
	help_appearance = { en = "Choose a method, drag A/R/G/B or click a number for exact entry. Saved per group, including repeats and shared recipes. Natural stimm keeps vanilla gameplay buffs on supported breeds. Other usable methods change visuals only. Prerequisite methods show what is missing and apply no colour. Compare with an untreated group of the same breed in a Realms mission." },
	mod_name = { en = "Realms Waves" },
	mod_description = {
		en = "Random enemy waves for Realms (LAN) sessions. Waves spawn near the squad but out of sight, ignore the director's spawn limits, and are picked at random or by an in-game vote. Everything is synced to all players' HUD. Edit waves in the wave editor (keybind below, or /rw_editor). Move the wave panel with the Custom HUD mod. Host needs the mod; clients need it to see the HUD and vote. Spawn distances are measured from the nearest player. The memory guard pauses spawning when the game uses that much memory (the game itself crashes at 1024 MB).",
	},

	mode = { en = "Wave selection mode" },
	mode_tarot = { en = "Tarot draw" },
	mode_random = { en = "Random countdown" },
	mode_vote = { en = "Votes (legacy)" },
	tarot_cards = { en = "Cards drawn" },
	tarot_seconds = { en = "Seconds before the pick" },
	tarot_default_cooldown = { en = "Default card cooldown" },

	group_timing = { en = "Timing and voting" },
	initial_delay = { en = "First wave delay" },
	interval_min = { en = "Minimum time between waves" },
	interval_max = { en = "Maximum time between waves" },
	vote_duration = { en = "Final vote window" },
	ballot_size = { en = "Candidates on a ballot" },
	novote_fallback = { en = "If nobody votes" },
	fallback_random = { en = "Pick a candidate at random" },
	fallback_skip = { en = "Skip this wave" },

	group_spawn = { en = "Spawning" },
	max_per_wave = { en = "Max enemies per wave" },
	max_alive = { en = "Max wave enemies alive" },
	heap_guard_mb = { en = "Memory guard (pause above)" },
	unit_megabytes = { en = "MB" },
	min_distance = { en = "Min spawn distance" },
	max_distance = { en = "Max spawn distance" },
	monster_min_distance = { en = "Monster min spawn distance" },
	monster_max_distance = { en = "Monster max spawn distance" },

	group_multipliers = { en = "Enemy number multipliers (apply to every wave)" },
	mult_normal = { en = "Normal and elite enemies" },
	mult_boss = { en = "Bosses (incl. twins)" },
	mult_special = { en = "Specials (hounds...)" },
	unit_percent = { en = "pct" },

	group_controls = { en = "Keys" },
	open_editor_bind = { en = "Open the wave editor" },
	vote_1_bind = { en = "Vote for option 1" },
	vote_2_bind = { en = "Vote for option 2" },
	vote_3_bind = { en = "Vote for option 3" },
	vote_4_bind = { en = "Vote for option 4" },
	vote_5_bind = { en = "Vote for option 5" },

	group_hud = { en = "HUD and debug" },
	hud_enabled = { en = "Show wave panel" },
	hud_show_percent = { en = "Show chances in the vote" },
	colour_enemies = { en = "Colour enemy names" },
	colour_spidey = { en = "Use Spidey Sense colours" },
	interval_random = { en = "Random time between waves" },
	pool_all_players = { en = "Use everyone's waves" },
	anti_snowball = { en = "Anti-snowballing" },
	anti_snowball_delay = { en = "Delay when someone dies" },
	debug = { en = "Debug logging" },

	unit_seconds = { en = "s" },
	unit_meters = { en = "m" },
	unit_minutes = { en = "min" },
	unit_pixels = { en = "px" },

	-- The Spread: the timeline of the reveal, on your own screen only
	group_spread = { en = "The Spread (your screen)" },
	tarot_scale = { en = "HUD size" },
	tarot_opacity = { en = "HUD opacity" },
	tarot_timer_below = { en = "Timer below the cards" },
	tarot_hide_icon = { en = "Hide the corner symbol" },
	tarot_ping = { en = "Ping when a card is back" },
	tarot_font = { en = "Font of the cards" },
	font_novarese_bold = { en = "Novarese Bold" },
	font_novarese = { en = "Novarese" },
	font_friz = { en = "Friz Quadrata" },
	font_proxima = { en = "Proxima Nova" },
	font_rexlia = { en = "Rexlia" },
	font_machine = { en = "Machine" },
	tarot_roulette = { en = "Roulette" },
	tarot_winner = { en = "Winner shown" },
	tarot_eye_open = { en = "Eye opening" },
	tarot_eye_size = { en = "Eye size" },
	tarot_rot_short = { en = "Rot, shortest cooldown" },
	tarot_rot_long = { en = "Rot, longest cooldown" },
	tarot_longest = { en = "Longest cooldown" },

	-- HUD panel (always localized with arguments, so "%%" is a literal percent sign)
	hud_wave_in = { en = "Next wave in %s" },
	hud_wave_in_vote = { en = "Next wave in %s. Vote: %s" },
	hud_vote_now = { en = "VOTE NOW: %s left. %s" },
	hud_incoming = { en = "WAVE INCOMING: %s" },
	hud_paused = { en = "(PAUSED)" },
	hud_card_in = { en = "Card revealed in" },
	hud_next_card = { en = "Next card in" },
	hud_card_drawn = { en = "The card is drawn" },
	hud_empty_tarot = { en = "No card is in the draw (open the wave editor)" },
	hud_all_cooling = { en = "Every card is resting" },
	msg_anti_snowball = { en = "RealmsWaves: a player died, the wave timers are delayed by %s seconds." },
	hud_no_votes = { en = "No votes, wave skipped" },
	hud_empty = { en = "Waves: nothing to draw (open the wave editor). Timed waves still run." },
	hud_line = { en = "%s  %s (%s%%)" },
	hud_line_votes = { en = "%s  %s (%s%%)  [%d]" },
	hud_line_plain = { en = "%s  %s" },
	hud_line_votes_plain = { en = "%s  %s  [%d]" },
	vote_cast = { en = "Voted %d: %s" },

	-- Wave editor
	view_title = { en = "The Grandfather's Tarot" },
	-- the screens of one card: its enemies (and the picker, Mods and Custom) and its face
	view_title_cauldron = { en = "The Grandfather's Cauldron" },
	view_title_mirror = { en = "The Grandfather's Mirror" },
	-- the Cauldron's shelf, stage and quick face (docs/08)
	tab_enemies = { en = "Enemies" },
	shelf_title = { en = "Add to this card" },
	shelf_hint = { en = "Click to add one. The card follows." },
	faction_adds = { en = "Adds:" },
	faction_dreg = { en = "Dreg" },
	faction_scab = { en = "Scab" },
	band_fodder = { en = "Fodder" },
	band_elite = { en = "Elites" },
	band_special = { en = "Specials" },
	band_boss = { en = "Bosses" },
	spawn_label = { en = "How it spawns" },
	stage_caption = { en = "The card, as the Deck draws it" },
	stage_stats = { en = "Threat %d  \194\183  %d enemies  \194\183  %s percent of the draw" },
	stage_stats_off = { en = "Out of the draw: it will not be dealt" },
	btn_preview_cooldown = { en = "Preview cooldown" },
	btn_quickface = { en = "Whisper and cooldown" },
	quick_label = { en = "Face" },
	lbl_threat = { en = "Threat" },
	btn_thr_auto = { en = "Auto" },
	btn_thr_hand = { en = "By hand" },
	msg_max_groups = { en = "RealmsWaves: a card holds at most 12 groups of enemies." },
	view_desc_list = {
		en = "Every card that can be drawn. Click a card to put it in or out of the draw; Edit opens it. Only the host's settings are used in a session.",
	},
	deck_count = { en = "%d in the draw" },
	deck_caption = { en = "Click a card to switch it, its pips for its chance, right click to edit, hold it and drop it on another to swap them" },
	sort_label = { en = "Sort by" },
	sort_threat = { en = "Threat" },
	sort_rarity = { en = "Rarity" },
	sort_enemies = { en = "Enemies" },
	sort_face = { en = "Face" },
	tile_pip_hover = { en = "%s: chance %d of 10" },
	-- custom mods of an enemy group (the "Custom" button beside "Mods")
	btn_tune = { en = "Custom" },
	btn_tune_reset = { en = "Reset" },
	col_percent = { en = "Percent" },
	view_desc_tune = { en = "Custom mods of %s: in percent of the normal value, 100 = unchanged. They are applied to every enemy of this group when it spawns." },
	bottom_tune_title = { en = "Custom mods: %s" },
	popup_tune_title = { en = "%s of %s, in percent" },
	popup_tune_hint = { en = "From %d to %d. 100 = unchanged." },
	tune_health = { en = "Health" },
	tune_health_info = { en = "Maximum health. 200 = twice as much. %d to %d." },
	tune_size = { en = "Size" },
	tune_size_info = { en = "Model size, %d to %d. A burster's blast grows with it. Others see it only if they have this mod. Hit areas may not grow." },
	tune_speed = { en = "Run speed" },
	tune_speed_info = { en = "How fast it walks and runs after you. %d to %d." },
	tune_gap = { en = "Time between attacks" },
	tune_gap_info = { en = "How long it waits before it can attack again: 50 = half the wait, 200 = twice as long. Chains keep every hit. %d to %d." },
	tune_fire = { en = "Gunner fire rate" },
	tune_fire_info = { en = "Time between two shots of shooters and gunners. %d to %d." },
	tune_burst = { en = "Shots per burst" },
	tune_burst_info = { en = "Shots in one burst of rifles and gunners (not sniper, plasma, shotgun). %d to %d." },
	tune_mass = { en = "Hit mass" },
	tune_explosion = { en = "Explosion damage taken" },
	tune_explosion_info = { en = "Share of explosion damage it takes: 50 = half, 0 = none. %d to %d." },
	tune_dot = { en = "Damage over time taken" },
	tune_dot_info = { en = "Share of burning, toxin and bleeding damage it takes: 50 = half, 0 = none. %d to %d." },
	tune_mass_info = { en = "How much of a swing it soaks up: more = fewer enemies cut per swing. %d to %d." },
	tile_in = { en = "In the draw" },
	tile_off = { en = "Out of the draw" },
	tile_cooling = { en = "Back in" },
	tile_ready = { en = "Ready" },
	tile_edit = { en = "Edit" },
	tile_rare = { en = "rare" },
	tile_repeats = { en = "and it repeats" },
	tile_more = { en = "+%d more" },
	tile_no_enemies = { en = "No enemies yet" },
	tile_blank_title = { en = "Name it" },
	tile_blank_hint = { en = "Pick a suit and add enemies. The threat is worked out for you." },
	view_desc_detail = { en = "Editing: %s" },
	view_desc_picker = { en = "Pick an enemy to add to: %s" },
	col_on = { en = "On" },
	col_wave = { en = "Wave" },
	col_composition = { en = "Composition" },
	col_chance = { en = "Chance" },
	btn_keep_pick_on = { en = "Random groups: one roll per wave" },
	btn_keep_pick_off = { en = "Random groups: a roll for every unit" },
	col_share = { en = "Share" },
	col_enemy = { en = "Enemy" },
	col_count = { en = "Brood" },
	col_id = { en = "Breed id" },
	bottom_list_title = { en = "The two numbers are the time between cards. The blank card makes a card of your own." },
	bottom_detail_title = { en = "%s: %d enemies in total" },
	hint_list = {
		en = "Click a card to put it in or out of the draw (a card out of the draw is dimmed). Edit in the corner of a card opens it: name, enemies, chance, cooldown and more. The ten pips are the card's chance (1 to 10); the strip above shows how likely each card is to be dealt into a hand, among the cards that are not resting. The blank card makes a card of your own. Spreads (top right) saves and loads whole setups. Delete (inside a card) removes any card, the default ones too: they stay hidden until you press Restore defaults, which also resets every other change. The two numbers at the bottom are the time between cards; More options has the rest of the timing and display settings.",
	},
	view_desc_mods = { en = "Modifiers for: %s" },
	col_modifier = { en = "Modifier" },
	col_effect = { en = "What it does" },
	btn_mods = { en = "Mods" },
	note_havoc_only = { en = "(Havoc missions only)" },
	hint_mods = {
		en = "Tick the conditions to force onto this group, even if the mission did not load them (e.g. Purple or Enraged on 3 crushers). They are added as buffs right after the enemies spawn. In the text editor, write them in brackets: 3 crushers[enraged+garden]. Their visuals and effects are the game's own.",
	},
	-- Settings screen (timing, voting, display)
	btn_settings = { en = "More options" },
	btn_default = { en = "Restore defaults" },
	bottom_list_deleted = { en = "%s default waves are deleted. Restore defaults brings them back." },
	extra_not_random = { en = "(not used: random is off)" },
	msg_defaults_restored = { en = "RealmsWaves: every wave is back to the defaults (Undo last load on the Presets screen restores your previous waves)." },
	help_detail = { en = "Edit one card. The card on the right follows every change. Click an enemy on the shelf to add one (the Dreg / Scab switch chooses which kind); the - and + of a row change its brood (how many of that enemy), Mods adds Havoc-style conditions and Custom changes health, size, speed, attack speed, fire rate, burst and hit mass. Under the card: its suit, its threat and its chance; the whisper and the cooldown are on the Face tab. How it spawns: spread, repeats, its own min and max spawn distance and a fixed timer (a card with a fixed timer ignores its chance and spawns every N seconds). Share wave gives you its text, or paste a friend's card over it." },
	help_picker = { en = "Click an enemy to add it. Just start typing to search. The button next to Search chooses whether you stay here after adding, to add several in a row, or go back to the wave." },
	help_preset_view = { en = "Load this setup replaces ALL your waves with the ones stored here (an empty slot loads the default waves). Save current waves here stores what you have now. Export gives you text to send to a friend, Import pastes theirs into this slot. Undo last load brings your previous waves back once." },
	btn_delete = { en = "Delete" },
	btn_create = { en = "Create" },
	btn_reset = { en = "Reset" },
	btn_sure = { en = "Sure?" },
	col_setting = { en = "Setting" },
	col_what_it_does = { en = "What it does" },
	col_value = { en = "Value" },
	view_desc_settings = { en = "More options: timing, voting and display. Click a row to change it. The same options are in the mod's options menu. Timing and voting are host settings." },
	hint_settings = {
		en = "Waves arrive after a time between the minimum and the maximum, or after exactly the minimum when the time is not random. The wave names and chances are shown from the start of the wait; the vote is highlighted during the final vote window.",
	},
	set_mode = { en = "Players vote on the next wave" },
	set_mode_info = { en = "On: the old vote mode, players pick between waves with the vote keys. Off: the Tarot draw. The Random countdown is chosen in the mod options. Host setting." },
	set_interval_random = { en = "Random time between waves" },
	set_interval_random_info = { en = "On: a random time between the minimum and maximum below. Off: always the same time, the minimum. Host setting." },
	set_interval_min = { en = "Minimum time between waves" },
	set_interval_min_info = { en = "Seconds. The shortest wait until the next wave. Host setting." },
	set_interval_fixed = { en = "Time between waves" },
	set_interval_fixed_info = { en = "Seconds. Every wave arrives after exactly this long. Host setting." },
	set_interval_max = { en = "Maximum time between waves" },
	set_interval_max_info = { en = "Seconds. The longest wait. Only used while the time is random. Host setting." },
	set_initial_delay = { en = "First wave extra delay" },
	set_initial_delay_info = { en = "Seconds added to the wait before the first wave of a mission. Host setting." },
	set_vote_duration = { en = "Wave names shown (vote window)" },
	set_vote_duration_info = { en = "Seconds before a wave arrives that its vote is open and highlighted. Never longer than the wait. Host setting." },
	set_ballot_size = { en = "Waves on a vote ballot" },
	set_ballot_size_info = { en = "How many different waves players can vote between (2 to 5). Host setting." },
	set_pool_all_players = { en = "Use everyone's waves" },
	set_pool_all_players_info = { en = "On: the enabled waves of every player with the mod join the draw, not only the host's. Identical waves count once. Host setting." },
	set_hud_show_percent = { en = "Show chances in the vote" },
	set_hud_show_percent_info = { en = "Your screen only: show each wave's chance (percent) next to its name in the wave panel." },
	set_colour_enemies = { en = "Colour enemy names" },
	set_colour_enemies_info = { en = "Your screen only: colour enemy names in this editor by type (special, boss, elite...)." },
	set_colour_spidey = { en = "Use Spidey Sense colours" },
	set_colour_spidey_info = { en = "Take an enemy's colour from your Spidey Sense settings when that mod is installed." },

	-- Sharing one wave
	btn_share = { en = "Share wave" },
	btn_wimport = { en = "Import card" },
	btn_face = { en = "Face" },
	btn_change = { en = "Change" },
	view_desc_face = { en = "Card face of: %s" },
	bottom_face_title = { en = "%s: suit, threat, whisper and the look of its cooldown. The preview shows the card as the Deck draws it." },
	help_face = {
		en = "Click a suit to give the card its colours and mark; the suggested one follows the enemies (a boss suggests Fateful, specials Blight, a horde of more than 60 without elites Swarm). Threat is worked out from the enemies (1 to 5) unless you set it with + and -; the line under the rows shows how. The whisper is one short line, empty uses the suit's own. Cooldown look: Automatic uses the murmur for Murmur cards and rot for the rest. The cooldown is how long the card rests after it is drawn.",
	},
	help_tune = {
		en = "Each value is a percent of what the game normally gives this enemy: 100 = unchanged, 150 = half again as much, 50 = half. Click a number to type it, Reset puts it back to 100. They are applied right after the enemy spawns, on the host. Health, run speed and hit mass reach every player through the game itself. Size is sent to the other players that have this mod (others see the normal size), and only the model grows, maybe not the areas you can hit. Time between attacks shortens (below 100) or lengthens (above 100) the wait after a melee attack: the swing itself is not faster, and a chain of hits keeps every hit. The fire rate and the burst work on the attacks that read them (rifles and gunners; not snipers, plasma or shotguns). In the text editor they follow the modifiers in braces: 3 crushers[enraged]{health=150 size=130}.",
	},
	suit_desc_plague = { en = "Nurgle's blessings: tougher enemies that heal and corrupt. Olive card, bile green, an eye." },
	suit_desc_murmur = { en = "The dark ones: stagger-immune, armoured, hard to see coming. Near-black card, a half moon." },
	suit_desc_rage = { en = "Speed and aggression: fast melee, chargers, hounds. Burnt-brown card, rust, a flame." },
	suit_desc_blight = { en = "Toxic and explosive: gas, bursters, bombers. Mustard-olive card, pus yellow, a drop." },
	suit_desc_swarm = { en = "Numbers over strength: hordes of fodder. Ash-grey olive, quiet on purpose, a cluster of dots." },
	suit_desc_fateful = { en = "Bosses and last stands. Black card, bone text, brass frame, a four-point star." },
	suit_desc_volley = { en = "Ranged fire: gunners, shooters, snipers. Steel-blue card, a crosshair." },
	suit_desc_snare = { en = "Control: trappers, netters, anything that holds you down. Sea-green card, linked rings." },
	suit_desc_brute = { en = "Heavy hitters: ogryns, crushers, bulwarks. Brick-red card, a plated square." },
	suit_desc_fester = { en = "Pox and rot: bursters, plague carriers, boils. Flesh-pink card, a swollen boil." },
	suit_desc_dusk = { en = "Ambush and the dark hour. Indigo card, a setting sun." },
	suit_desc_warp = { en = "The Daemonhost. Purple card, an eye in a triangle. Suggested for any card that holds one." },
	face_suggested = { en = "(suggested for these enemies)" },
	face_threat = { en = "Threat" },
	face_threat_auto = { en = "Worked out from the enemies, see below. + sets it by hand." },
	face_threat_own = { en = "Set by hand. - down to auto works it out again." },
	face_whisper = { en = "Whisper" },
	face_whisper_suit = { en = "(the suit's own line) %s" },
	face_look = { en = "Cooldown look" },
	look_rot = { en = "Rot and renewal" },
	look_whisper = { en = "The murmur returns" },
	look_vial = { en = "The vial fills" },
	face_look_auto = { en = "Automatic: %s" },
	face_cooldown = { en = "Cooldown" },
	face_cooldown_info = { en = "Seconds the card rests after it is drawn: 30 s steps up to %d minutes (the longest cooldown option)." },
	face_numbers = { en = "Threat %d by the numbers: %d enemies give %d" },
	-- the Mirror (docs/08)
	mirror_suit = { en = "Suit" },
	mirror_suit_hint = { en = "Sets the colours, the corner icon and the default look of the cooldown." },
	mirror_threat = { en = "Threat" },
	mirror_threat_hint = { en = "Worked out from the enemies. Click a diamond to set it by hand." },
	mirror_whisper = { en = "Whisper" },
	mirror_whisper_hint = { en = "The line in quotes on the card. Empty borrows the suit's own line." },
	mirror_cooldown = { en = "Cooldown" },
	mirror_cooldown_hint = { en = "Seconds the card rests after it is drawn. Steps of 30 s, up to %d minutes." },
	mirror_cooldown_extra = { en = "%d seconds before it can be drawn again" },
	mirror_suggested = { en = "Suggested" },
	hand_caption = { en = "In the hand, as the Spread draws it" },
	btn_whisper_suit = { en = "Use the suit's line" },
	btn_look_auto = { en = "Automatic for this suit" },
	btn_reset_face = { en = "Reset face" },
	look_rot_desc = { en = "Grey, brown, ochre, then the suit's colour." },
	look_whisper_desc = { en = "The whisper comes back letter by letter." },
	look_vial_desc = { en = "Pus rises from the bottom of the card." },
	look_automatic = { en = "Automatic" },
	look_sample = { en = "Do you hear it?" },
	face_elites = { en = ", elites +1" },
	face_specials = { en = ", specials +1" },
	face_boss = { en = ", a boss +2" },
	face_override = { en = "Set by hand to %d." },
	face_suggest = { en = "Suggested suit: %s." },
	popup_whisper_title = { en = "Whisper of %s" },
	popup_whisper_hint = { en = "At most 40 characters. Leave it empty to use the suit's own line." },
	popup_threat_title = { en = "Threat of %s" },
	popup_threat_hint = { en = "0 works it out from the enemies, 1 to 5 sets it by hand." },
	popup_share_title = { en = "Share: %s" },
	popup_share_hint_copied = { en = "Copied to your clipboard. To import a friend's wave OVER THIS wave, paste it here and press OK." },
	popup_share_hint = { en = "Press Ctrl+A then Ctrl+C to copy. To import a friend's wave OVER THIS wave, paste it here and press OK." },
	popup_wimport_title = { en = "Import a wave" },
	popup_wimport_hint = { en = "Paste a friend's wave text (Ctrl+V), then OK. It goes into the first free custom slot (%s)." },
	popup_wimport_hint_filled = { en = "Your clipboard holds a wave, filled in below. OK imports it into the first free custom slot (%s)." },
	msg_wave_replaced = { en = "Replaced this wave with the imported one: %s" },
	msg_wave_imported = { en = "Imported wave %s into %s." },
	msg_no_free_slot = { en = "All custom slots are in use. Delete one first, or open a wave and use Share to import over it." },

	-- Presets
	btn_presets = { en = "Spreads" },
	btn_open = { en = "Open" },
	btn_pload = { en = "Load this setup" },
	btn_psave = { en = "Save current waves here" },
	btn_pexport = { en = "Export (copy)" },
	btn_pimport = { en = "Import (paste)" },
	btn_pundo = { en = "Undo last load" },
	btn_pclear = { en = "Clear slot" },
	col_preset = { en = "Preset" },
	col_preset_holds = { en = "What it holds" },
	view_desc_presets = { en = "Five slots for your whole wave setup. Open a slot to save your current waves into it, load it back, or share it with friends." },
	view_desc_preset = { en = "Preset %s: %s" },
	hint_presets = {
		en = "A preset stores every wave you changed: names, enemies, enabled, chances, cooldowns, spread and repeats. Loading one replaces ALL your waves with it (Undo last load brings the previous setup back). Export gives you one line of text to send to a friend, who opens a slot and presses Import.",
	},
	preset_slot_empty = { en = "(empty)" },
	preset_slot_empty_long = { en = "Empty slot. Press Save current waves here to store your waves, or Import to paste a friend's preset." },
	preset_slot_info = { en = "%s changed waves: %s" },
	preset_slot_broken = { en = "(damaged, clear it or import again: %s)" },
	preset_all_default = { en = "Everything at the default setup" },
	preset_view_title = { en = "%s changed waves in this preset. Waves not listed load as the defaults." },
	preset_wave_disabled = { en = "(disabled)" },
	preset_saved = { en = "Saved %s: %s changed waves stored." },
	preset_loaded = { en = "Loaded %s (%s changed waves). Undo last load restores your previous waves." },
	preset_undone = { en = "Your previous waves are back." },
	preset_cleared = { en = "Slot cleared." },
	preset_nothing_to_load = { en = "This slot is damaged, nothing to load. Clear it or import again." },
	preset_loaded_blank = { en = "Slot %s is empty: loaded the default waves. Save current waves here to store a setup in it. Undo last load restores your previous waves." },
	preset_nothing_to_export = { en = "This slot is empty, nothing to export." },
	preset_nothing_to_undo = { en = "Nothing to undo." },
	preset_save_first = { en = "Save your current waves into this slot first, then you can rename it." },
	preset_imported = { en = "Imported %s (%s changed waves)." },
	preset_imported_skipped = { en = "Imported %s (%s changed waves). %s waves were skipped, this version does not know them." },
	preset_undo_name = { en = "Before last load" },
	popup_preset_rename_title = { en = "Rename preset %s" },
	popup_export_title = { en = "Export: %s" },
	popup_export_hint_copied = { en = "Copied to your clipboard. Paste it to a friend (Ctrl+V). They open a slot and press Import (paste)." },
	popup_export_hint = { en = "Could not copy automatically: press Ctrl+A then Ctrl+C in the box, then paste it to a friend." },
	popup_import_title = { en = "Import into slot %s" },
	popup_import_hint = { en = "Paste the preset text here (Ctrl+V), then OK. It replaces whatever is in slot %s." },
	popup_import_hint_filled = { en = "Your clipboard already holds a preset, filled in below. OK imports it into slot %s and replaces what is there." },

	btn_search = { en = "Search enemies" },
	btn_search_active = { en = "Search: %s" },
	btn_stay_on = { en = "Stays here after adding" },
	btn_stay_off = { en = "Back to wave after adding" },
	btn_random_off = { en = "Random group: off" },
	btn_random_on = { en = "Random group: ON" },
	btn_random_done = { en = "Create group (%s)" },
	picker_random_status = { en = "Random group: %s." },
	picker_random_none = { en = "click two or more enemies, then Create group" },
	picker_random_need_two = { en = "Pick at least two enemies for a random group." },
	picker_random_added = { en = "Added a random group of %s enemies." },
	col_cooldown = { en = "Cooldown" },
	picker_added = { en = "Added %s (now %s in this wave)." },
	popup_search_title = { en = "Search enemies" },
	popup_search_hint = { en = "Type part of a name, alias or type (boss, special, elite, horde). The list filters as you type. Enter keeps it, Esc undoes. (Typing anywhere on this screen opens this box.)" },
	picker_status = { en = "Showing all %s of %s enemies" },
	picker_status_filtered = { en = "Showing %s of %s enemies matching: %s" },
	btn_back = { en = "Back" },
	btn_rename = { en = "Rename" },
	btn_edit_text = { en = "Edit as text" },
	btn_add_enemy = { en = "Search all enemies" },
	btn_enabled_on = { en = "In the draw" },
	btn_enabled_off = { en = "Out of the draw" },
	btn_reset_default = { en = "Reset to default" },
	btn_reset_clear = { en = "Clear this slot" },
	btn_edit = { en = "Edit" },
	btn_remove = { en = "Remove" },
	btn_add = { en = "Add" },
	col_repeat = { en = "Added each repeat" },
	col_same = { en = "Same" },
	lbl_dmin = { en = "Min distance" },
	lbl_dmax = { en = "Max distance" },
	val_auto = { en = "auto" },
	extra_dist_auto = { en = "= %s m" },
	extra_dist_own = { en = "m" },
	lbl_timer = { en = "Fixed timer" },
	val_off = { en = "off" },
	extra_timer_off = { en = "by chance" },
	extra_timer_on = { en = "s: no chance" },
	extra_timer_wave = { en = "not drawn: it runs on its own fixed timer" },
	extra_timer_ignored = { en = "(ignored: fixed timer)" },
	share_timer = { en = "every %s s" },
	popup_timer_title = { en = "Fixed timer of %s in seconds (0 = off and drawn by chance, otherwise at least 5)" },
	popup_dmin_title = { en = "Minimum spawn distance of %s in metres (0 = use the options, up to 200)" },
	popup_dmax_title = { en = "Maximum spawn distance of %s in metres (0 = use the options, up to 200)" },
	lbl_spread = { en = "Spread radius" },
	extra_meters = { en = "m" },
	lbl_repeat_every = { en = "Repeat every" },
	extra_seconds = { en = "seconds" },
	extra_no_repeat = { en = "no repeat" },
	lbl_repeat_for = { en = "Repeat for" },
	extra_seconds_short = { en = "s" },
	popup_rep_title = { en = "Enemies added on every repeat: %s (0 to 60)" },
	popup_spread_title = { en = "Spread radius of %s in metres (0 to 100)" },
	popup_every_title = { en = "Repeat %s every this many seconds (1 to 600)" },
	popup_for_title = { en = "Keep repeating %s for this many seconds (0 to 3600)" },
	lbl_chance = { en = "Chance" },
	lbl_cooldown = { en = "Cooldown" },
	extra_share = { en = "= %s percent of the draw" },
	extra_not_drawn = { en = "not drawn (disabled, empty or chance 0)" },
	extra_cooldown = { en = "seconds before it can repeat" },
	row_empty_slot = { en = "(empty slot)" },
	list_range = { en = "%s - %s of %s" },
	msg_need_one_enemy = { en = "RealmsWaves: a built-in wave needs at least one enemy (use Reset to default to restore it)." },
	popup_chance_title = { en = "Chance of %s (0 to 10)" },
	popup_count_title = { en = "Brood of %s" },
	popup_cooldown_title = { en = "Cooldown of %s in seconds (0 to 3600)" },
	popup_rename_title = { en = "New name for this wave" },
	popup_recipe_title = { en = "Edit the enemies as text" },
	popup_recipe_hint = { en = "Example: 5 trappers, 3 crushers[enraged+garden]@2 (+2 on every repeat) or 3 crushers@= (the same 3 again on every repeat). Random pick: 1 plague ogryn|chaos spawn." },
	popup_number_error = { en = "Enter a whole number from %s to %s" },
	popup_hint_number = { en = "Type a number, Enter to confirm, Esc to cancel" },
	popup_hint_text = { en = "Type the text, Enter to confirm, Esc to cancel" },
	popup_ok = { en = "OK" },
	popup_cancel = { en = "Cancel" },
}
