-- NOTE: DMF runs every localized string through string.format. A bare "%" is an
-- error ("invalid option '%' to 'format'"); write "%%" only in strings that are
-- always localized with arguments, otherwise avoid the character (use "percent").
return {
	mod_name = { en = "Realms Waves" },
	mod_description = {
		en = "Random enemy waves for Realms (LAN) sessions. Waves spawn near the squad but out of sight, ignore the director's spawn limits, and are picked at random or by an in-game vote. Everything is synced to all players' HUD. Edit waves in the wave editor (keybind below, or /rw_editor). Move the wave panel with the Custom HUD mod. Host needs the mod; clients need it to see the HUD and vote. Spawn distances are measured from the nearest player. The memory guard pauses spawning when the game uses that much memory (the game itself crashes at 1024 MB).",
	},

	mode = { en = "Wave selection mode" },
	mode_random = { en = "Random (host rolls)" },
	mode_vote = { en = "Vote (players choose)" },

	group_timing = { en = "Timing and voting" },
	initial_delay = { en = "First wave delay" },
	interval_min = { en = "Minimum time between waves" },
	interval_max = { en = "Maximum time between waves" },
	vote_duration = { en = "Final vote window" },
	ballot_size = { en = "Candidates on a ballot" },
	novote_fallback = { en = "If nobody votes" },
	fallback_random = { en = "Pick a candidate at random" },
	fallback_skip = { en = "Skip this wave" },

	group_spawn = { en = "Spawning" },
	max_per_wave = { en = "Max enemies per wave" },
	max_alive = { en = "Max wave enemies alive" },
	heap_guard_mb = { en = "Memory guard (pause above)" },
	unit_megabytes = { en = "MB" },
	min_distance = { en = "Min spawn distance" },
	max_distance = { en = "Max spawn distance" },
	monster_min_distance = { en = "Monster min spawn distance" },
	monster_max_distance = { en = "Monster max spawn distance" },

	group_multipliers = { en = "Enemy number multipliers (apply to every wave)" },
	mult_normal = { en = "Normal and elite enemies" },
	mult_boss = { en = "Bosses (incl. twins)" },
	mult_special = { en = "Specials (hounds...)" },
	unit_percent = { en = "pct" },

	group_controls = { en = "Keys" },
	open_editor_bind = { en = "Open the wave editor" },
	vote_1_bind = { en = "Vote for option 1" },
	vote_2_bind = { en = "Vote for option 2" },
	vote_3_bind = { en = "Vote for option 3" },
	vote_4_bind = { en = "Vote for option 4" },
	vote_5_bind = { en = "Vote for option 5" },

	group_hud = { en = "HUD and debug" },
	hud_enabled = { en = "Show wave panel" },
	hud_show_percent = { en = "Show chances in the vote" },
	colour_enemies = { en = "Colour enemy names" },
	colour_spidey = { en = "Use Spidey Sense colours" },
	interval_random = { en = "Random time between waves" },
	debug = { en = "Debug logging" },

	unit_seconds = { en = "s" },
	unit_meters = { en = "m" },

	-- HUD panel (always localized with arguments, so "%%" is a literal percent sign)
	hud_wave_in = { en = "Next wave in %s" },
	hud_wave_in_vote = { en = "Next wave in %s. Vote: %s" },
	hud_vote_now = { en = "VOTE NOW: %s left. %s" },
	hud_incoming = { en = "WAVE INCOMING: %s" },
	hud_no_votes = { en = "No votes, wave skipped" },
	hud_empty = { en = "Waves: no wave enabled (open the wave editor)" },
	hud_line = { en = "%s  %s (%s%%)" },
	hud_line_votes = { en = "%s  %s (%s%%)  [%d]" },
	hud_line_plain = { en = "%s  %s" },
	hud_line_votes_plain = { en = "%s  %s  [%d]" },
	vote_cast = { en = "Voted %d: %s" },

	-- Wave editor
	view_title = { en = "Realms Waves: Wave Editor" },
	view_desc_list = {
		en = "Every wave that can be drawn. Tick to enable, change the chance weight, or click a wave to rename it and change its enemies. Only the host's settings are used in a session.",
	},
	view_desc_detail = { en = "Editing: %s" },
	view_desc_picker = { en = "Pick an enemy to add to: %s" },
	col_on = { en = "On" },
	col_wave = { en = "Wave" },
	col_composition = { en = "Composition" },
	col_chance = { en = "Chance weight" },
	col_share = { en = "Share" },
	col_enemy = { en = "Enemy" },
	col_count = { en = "Weight" },
	col_id = { en = "Breed id" },
	bottom_list_title = { en = "Custom slots are empty until you add enemies to them" },
	bottom_detail_title = { en = "%s: %d enemies in total" },
	hint_list = {
		en = "Click a wave's row to edit it (rename it, change its enemies, chance, cooldown and more). The share column is each wave's chance as a part of all enabled waves, so the shares always add up to 100 percent. Set a weight to 0 or untick a wave to remove it from the draw. Press Create on an empty Custom slot (or click it) to build your own wave: name it, then add enemies. Delete empties a custom wave, Reset undoes your changes to a standard one.",
	},
	view_desc_mods = { en = "Modifiers for: %s" },
	col_modifier = { en = "Modifier" },
	col_effect = { en = "What it does" },
	btn_mods = { en = "Mods" },
	note_havoc_only = { en = "(Havoc missions only)" },
	hint_mods = {
		en = "Tick the conditions to force onto this group, even if the mission did not load them (e.g. Purple or Enraged on 3 crushers). They are added as buffs right after the enemies spawn. In the text editor, write them in brackets: 3 crushers[enraged+garden]. Their visuals and effects are the game's own.",
	},
	-- Settings screen (timing, voting, display)
	btn_settings = { en = "Timing and voting" },
	btn_delete = { en = "Delete" },
	btn_create = { en = "Create" },
	btn_reset = { en = "Reset" },
	btn_sure = { en = "Sure?" },
	col_setting = { en = "Setting" },
	col_what_it_does = { en = "What it does" },
	col_value = { en = "Value" },
	view_desc_settings = { en = "Timing, voting and display. Click a row to change it. The same options are in the mod's options menu. Timing and voting are host settings." },
	hint_settings = {
		en = "Waves arrive after a time between the minimum and the maximum, or after exactly the minimum when the time is not random. The wave names and chances are shown from the start of the wait; the vote is highlighted during the final vote window.",
	},
	set_mode = { en = "Players vote on the next wave" },
	set_mode_info = { en = "On: players pick between waves with the vote keys. Off: the host rolls the next wave by chance. Host setting." },
	set_interval_random = { en = "Random time between waves" },
	set_interval_random_info = { en = "On: a random time between the minimum and maximum below. Off: always the same time, the minimum. Host setting." },
	set_interval_min = { en = "Minimum time between waves" },
	set_interval_min_info = { en = "Seconds. The shortest wait until the next wave. Host setting." },
	set_interval_fixed = { en = "Time between waves" },
	set_interval_fixed_info = { en = "Seconds. Every wave arrives after exactly this long. Host setting." },
	set_interval_max = { en = "Maximum time between waves" },
	set_interval_max_info = { en = "Seconds. The longest wait. Only used while the time is random. Host setting." },
	set_initial_delay = { en = "First wave extra delay" },
	set_initial_delay_info = { en = "Seconds added to the wait before the first wave of a mission. Host setting." },
	set_vote_duration = { en = "Wave names shown (vote window)" },
	set_vote_duration_info = { en = "Seconds before a wave arrives that its vote is open and highlighted. Never longer than the wait. Host setting." },
	set_ballot_size = { en = "Waves on a vote ballot" },
	set_ballot_size_info = { en = "How many different waves players can vote between (2 to 5). Host setting." },
	set_hud_show_percent = { en = "Show chances in the vote" },
	set_hud_show_percent_info = { en = "Your screen only: show each wave's chance (percent) next to its name in the wave panel." },
	set_colour_enemies = { en = "Colour enemy names" },
	set_colour_enemies_info = { en = "Your screen only: colour enemy names in this editor by type (special, boss, elite...)." },
	set_colour_spidey = { en = "Use Spidey Sense colours" },
	set_colour_spidey_info = { en = "Take an enemy's colour from your Spidey Sense settings when that mod is installed." },

	-- Presets
	btn_presets = { en = "Presets" },
	btn_open = { en = "Open" },
	btn_pload = { en = "Load this setup" },
	btn_psave = { en = "Save current waves here" },
	btn_pexport = { en = "Export (copy)" },
	btn_pimport = { en = "Import (paste)" },
	btn_pundo = { en = "Undo last load" },
	btn_pclear = { en = "Clear slot" },
	col_preset = { en = "Preset" },
	col_preset_holds = { en = "What it holds" },
	view_desc_presets = { en = "Five slots for your whole wave setup. Open a slot to save your current waves into it, load it back, or share it with friends." },
	view_desc_preset = { en = "Preset %s: %s" },
	hint_presets = {
		en = "A preset stores every wave you changed: names, enemies, enabled, chance weights, cooldowns, spread and repeats. Loading one replaces ALL your waves with it (Undo last load brings the previous setup back). Export gives you one line of text to send to a friend, who opens a slot and presses Import.",
	},
	preset_slot_empty = { en = "(empty)" },
	preset_slot_empty_long = { en = "Empty slot. Press Save current waves here to store your waves, or Import to paste a friend's preset." },
	preset_slot_info = { en = "%s changed waves: %s" },
	preset_slot_broken = { en = "(damaged, clear it or import again: %s)" },
	preset_all_default = { en = "Everything at the default setup" },
	preset_view_title = { en = "%s changed waves in this preset. Waves not listed load as the defaults." },
	preset_wave_disabled = { en = "(disabled)" },
	preset_saved = { en = "Saved %s: %s changed waves stored." },
	preset_loaded = { en = "Loaded %s (%s changed waves). Undo last load restores your previous waves." },
	preset_undone = { en = "Your previous waves are back." },
	preset_cleared = { en = "Slot cleared." },
	preset_nothing_to_load = { en = "This slot is empty, nothing to load." },
	preset_nothing_to_export = { en = "This slot is empty, nothing to export." },
	preset_nothing_to_undo = { en = "Nothing to undo." },
	preset_save_first = { en = "Save your current waves into this slot first, then you can rename it." },
	preset_imported = { en = "Imported %s (%s changed waves)." },
	preset_imported_skipped = { en = "Imported %s (%s changed waves). %s waves were skipped, this version does not know them." },
	preset_undo_name = { en = "Before last load" },
	popup_preset_rename_title = { en = "Rename preset %s" },
	popup_export_title = { en = "Export: %s" },
	popup_export_hint_copied = { en = "Copied to your clipboard. Paste it to a friend (Ctrl+V). They open a slot and press Import (paste)." },
	popup_export_hint = { en = "Could not copy automatically: press Ctrl+A then Ctrl+C in the box, then paste it to a friend." },
	popup_import_title = { en = "Import into slot %s" },
	popup_import_hint = { en = "Paste the preset text here (Ctrl+V), then OK. It replaces whatever is in slot %s." },
	popup_import_hint_filled = { en = "Your clipboard already holds a preset, filled in below. OK imports it into slot %s and replaces what is there." },

	btn_search = { en = "Search enemies" },
	btn_search_active = { en = "Search: %s" },
	btn_stay_on = { en = "After adding: stay here (click to go back)" },
	btn_stay_off = { en = "After adding: back to wave (click to stay)" },
	picker_added = { en = "Added %s (now %s in this wave)." },
	popup_search_title = { en = "Search enemies" },
	popup_search_hint = { en = "Type part of a name, alias or type (boss, special, elite, horde). The list filters as you type. Enter keeps it, Esc undoes. (Typing anywhere on this screen opens this box.)" },
	picker_status = { en = "Showing all %s of %s enemies" },
	picker_status_filtered = { en = "Showing %s of %s enemies matching: %s" },
	btn_back = { en = "Back" },
	btn_rename = { en = "Rename" },
	btn_edit_text = { en = "Edit as text" },
	btn_add_enemy = { en = "Add enemy" },
	btn_enabled_on = { en = "Enabled: yes" },
	btn_enabled_off = { en = "Enabled: no" },
	btn_reset_default = { en = "Reset to default" },
	btn_reset_clear = { en = "Clear this slot" },
	btn_edit = { en = "Edit" },
	btn_remove = { en = "Remove" },
	btn_add = { en = "Add" },
	col_repeat = { en = "Added each repeat" },
	col_same = { en = "Same" },
	lbl_dmin = { en = "Min distance" },
	lbl_dmax = { en = "Max distance" },
	val_auto = { en = "auto" },
	extra_dist_auto = { en = "auto: %s m from the options" },
	extra_dist_own = { en = "m from the nearest player, this wave only" },
	popup_dmin_title = { en = "Minimum spawn distance of %s in metres (0 = use the options, up to 200)" },
	popup_dmax_title = { en = "Maximum spawn distance of %s in metres (0 = use the options, up to 200)" },
	lbl_spread = { en = "Spread radius" },
	extra_meters = { en = "m" },
	lbl_repeat_every = { en = "Repeat every" },
	extra_seconds = { en = "seconds" },
	extra_no_repeat = { en = "off: no repeats" },
	lbl_repeat_for = { en = "Repeat for" },
	extra_seconds_short = { en = "s" },
	popup_rep_title = { en = "Enemies added on every repeat: %s (0 to 60)" },
	popup_spread_title = { en = "Spread radius of %s in metres (0 to 100)" },
	popup_every_title = { en = "Repeat %s every this many seconds (1 to 600)" },
	popup_for_title = { en = "Keep repeating %s for this many seconds (0 to 3600)" },
	lbl_chance = { en = "Chance weight" },
	lbl_cooldown = { en = "Cooldown" },
	extra_share = { en = "= %s percent of all enabled waves" },
	extra_not_drawn = { en = "not drawn (disabled, empty or weight 0)" },
	extra_cooldown = { en = "seconds before it can repeat" },
	row_empty_slot = { en = "(empty slot)" },
	list_range = { en = "%s - %s of %s" },
	msg_need_one_enemy = { en = "RealmsWaves: a built-in wave needs at least one enemy (use Reset to default to restore it)." },
	popup_chance_title = { en = "Chance weight of %s (0 to 1000)" },
	popup_count_title = { en = "Weight of %s" },
	popup_cooldown_title = { en = "Cooldown of %s in seconds (0 to 3600)" },
	popup_rename_title = { en = "New name for this wave" },
	popup_recipe_title = { en = "Edit the enemies as text" },
	popup_recipe_hint = { en = "Example: 5 trappers, 3 crushers[enraged+garden]@2 (+2 on every repeat) or 3 crushers@= (the same 3 again on every repeat). Random pick: 1 plague ogryn|chaos spawn." },
	popup_number_error = { en = "Enter a whole number from %s to %s" },
	popup_hint_number = { en = "Type a number, Enter to confirm, Esc to cancel" },
	popup_hint_text = { en = "Type the text, Enter to confirm, Esc to cancel" },
	popup_ok = { en = "OK" },
	popup_cancel = { en = "Cancel" },
}
