-- NOTE: DMF runs every localized string through string.format. A bare "%" is an
-- error ("invalid option '%' to 'format'"); write "%%" only in strings that are
-- always localized with arguments, otherwise avoid the character (use "percent").
return {
	mod_name = { en = "Realms Waves" },
	mod_description = {
		en = "Random enemy waves for Realms (LAN) sessions. Waves spawn near the squad but out of sight, ignore the director's spawn limits, and are picked at random or by an in-game vote. Everything is synced to all players' HUD. Edit waves in the wave editor (keybind below, or /rw_editor). Move the wave panel with the Custom HUD mod. Host needs the mod; clients need it to see the HUD and vote.",
	},

	mode = { en = "Wave selection mode" },
	mode_random = { en = "Random (host rolls)" },
	mode_vote = { en = "Vote (players choose)" },

	group_timing = { en = "Timing and voting" },
	initial_delay = { en = "Extra delay before the first wave" },
	interval_min = { en = "Minimum time between waves" },
	interval_max = { en = "Maximum time between waves" },
	vote_duration = { en = "Final vote window (highlighted)" },
	ballot_size = { en = "Candidates on a ballot" },
	novote_fallback = { en = "If nobody votes" },
	fallback_random = { en = "Pick a candidate at random" },
	fallback_skip = { en = "Skip this wave" },

	group_spawn = { en = "Spawning" },
	max_per_wave = { en = "Max enemies per wave" },
	max_alive = { en = "Max wave enemies alive at once" },
	min_distance = { en = "Min spawn distance from nearest player" },
	max_distance = { en = "Max spawn distance from nearest player" },
	monster_min_distance = { en = "Monster min spawn distance" },
	monster_max_distance = { en = "Monster max spawn distance" },

	group_controls = { en = "Keys" },
	open_editor_bind = { en = "Open the wave editor" },
	vote_1_bind = { en = "Vote for option 1" },
	vote_2_bind = { en = "Vote for option 2" },
	vote_3_bind = { en = "Vote for option 3" },
	vote_4_bind = { en = "Vote for option 4" },
	vote_5_bind = { en = "Vote for option 5" },

	group_hud = { en = "HUD and debug" },
	hud_enabled = { en = "Show wave panel" },
	debug = { en = "Debug logging" },

	unit_seconds = { en = "s" },
	unit_meters = { en = "m" },
	unit_enemies = { en = "enemies" },
	unit_options = { en = "options" },

	-- HUD panel (always localized with arguments, so "%%" is a literal percent sign)
	hud_wave_in = { en = "Next wave in %s" },
	hud_wave_in_vote = { en = "Next wave in %s. Vote: %s" },
	hud_vote_now = { en = "VOTE NOW: %s left. %s" },
	hud_incoming = { en = "WAVE INCOMING: %s" },
	hud_no_votes = { en = "No votes, wave skipped" },
	hud_empty = { en = "Waves: no wave enabled (open the wave editor)" },
	hud_line = { en = "%s  %s (%s%%)" },
	hud_line_votes = { en = "%s  %s (%s%%)  [%d]" },
	vote_cast = { en = "Voted %d: %s" },

	-- Wave editor
	view_title = { en = "Realms Waves: Wave Editor" },
	view_desc_list = {
		en = "Every wave that can be drawn. Tick to enable, change the chance weight, or press Edit to rename it and change its enemies. Only the host's settings are used in a session.",
	},
	view_desc_detail = { en = "Editing: %s" },
	view_desc_picker = { en = "Pick an enemy to add to: %s" },
	col_on = { en = "On" },
	col_wave = { en = "Wave" },
	col_composition = { en = "Composition" },
	col_chance = { en = "Chance weight" },
	col_share = { en = "Share" },
	col_enemy = { en = "Enemy" },
	col_count = { en = "Count" },
	col_id = { en = "Breed id" },
	bottom_list_title = { en = "Custom slots are empty until you add enemies to them" },
	bottom_detail_title = { en = "%s: %d enemies in total" },
	hint_list = {
		en = "The share column is each wave's chance as a part of all enabled waves, so the shares always add up to 100 percent. Set a weight to 0 or untick a wave to remove it from the draw. Press Edit on a Custom slot to build your own wave: name it, then add enemies.",
	},
	view_desc_mods = { en = "Modifiers for: %s" },
	col_modifier = { en = "Modifier" },
	col_effect = { en = "What it does" },
	btn_mods = { en = "Mods" },
	note_havoc_only = { en = "(Havoc missions only)" },
	hint_mods = {
		en = "Tick the conditions to force onto this group, even if the mission did not load them (e.g. Garden or Enraged on 3 crushers). They are added as buffs right after the enemies spawn. In the text editor, write them in brackets: 3 crushers[enraged+garden]. Their visuals and effects are the game's own.",
	},
	btn_back = { en = "Back" },
	btn_rename = { en = "Rename" },
	btn_edit_text = { en = "Edit as text" },
	btn_add_enemy = { en = "Add enemy" },
	btn_enabled_on = { en = "Enabled: yes" },
	btn_enabled_off = { en = "Enabled: no" },
	btn_reset_default = { en = "Reset to default" },
	btn_reset_clear = { en = "Clear this slot" },
	btn_edit = { en = "Edit" },
	btn_remove = { en = "Remove" },
	btn_add = { en = "Add" },
	col_repeat = { en = "Added each repeat" },
	lbl_spread = { en = "Spread radius" },
	extra_meters = { en = "m" },
	lbl_repeat_every = { en = "Repeat every" },
	extra_seconds = { en = "seconds" },
	extra_no_repeat = { en = "off: no repeats" },
	lbl_repeat_for = { en = "Repeat for" },
	extra_seconds_short = { en = "s" },
	popup_rep_title = { en = "Enemies added on every repeat: %s (0 to 60)" },
	popup_spread_title = { en = "Spread radius of %s in metres (0 to 100)" },
	popup_every_title = { en = "Repeat %s every this many seconds (1 to 600)" },
	popup_for_title = { en = "Keep repeating %s for this many seconds (0 to 3600)" },
	lbl_chance = { en = "Chance weight" },
	lbl_cooldown = { en = "Cooldown" },
	extra_share = { en = "= %s percent of all enabled waves" },
	extra_not_drawn = { en = "not drawn (disabled, empty or weight 0)" },
	extra_cooldown = { en = "seconds before it can repeat" },
	row_empty_slot = { en = "(empty slot)" },
	list_range = { en = "%s - %s of %s" },
	msg_need_one_enemy = { en = "RealmsWaves: a built-in wave needs at least one enemy (use Reset to default to restore it)." },
	popup_chance_title = { en = "Chance weight of %s (0 to 1000)" },
	popup_count_title = { en = "Count of %s" },
	popup_cooldown_title = { en = "Cooldown of %s in seconds (0 to 3600)" },
	popup_rename_title = { en = "New name for this wave" },
	popup_recipe_title = { en = "Edit the enemies as text" },
	popup_recipe_hint = { en = "Example: 5 trappers, 3 crushers[enraged+garden]@2 (the @2 adds 2 more on every repeat). Random pick: 1 plague ogryn|chaos spawn. Enter confirms." },
	popup_number_error = { en = "Enter a whole number from %s to %s" },
	popup_hint_number = { en = "Type a number, Enter to confirm, Esc to cancel" },
	popup_hint_text = { en = "Type the text, Enter to confirm, Esc to cancel" },
	popup_ok = { en = "OK" },
	popup_cancel = { en = "Cancel" },
}
