-- NOTE: DMF runs every localized string through string.format. A bare "%" is an
-- error ("invalid option '%' to 'format'"); write "%%" only in strings that are
-- always localized with arguments, otherwise avoid the character (use "percent").
local L = {
	hud_card_drawn_beneficial = { en = "A blessing is drawn", ["pt-br"] = "Uma bênção é sorteada" },
	btn_appearance = { en = "Enemy colour experiments" },
	view_desc_appearance = { en = "Enemy colour experiments: %s" },
	appearance_strength_info = { en = "A = tint strength. Swatch previews the input colour; the game result depends on the method and enemy materials." },
	help_appearance = { en = "# Colour experiments\n- Choose a method, then drag *A R G B* or click a number to type it.\n- Saved per group, with its repeats and in shared cards.\n- *Natural stimm* keeps the game's own buffs on the enemies that support it. The other usable methods only change the look.\n- A method that needs something shows what is missing and applies no colour.\n- Compare with an untreated group of the same enemy in a Realms mission." },
	mod_name = { en = "The Grandfather's Tarot" },
	mod_description = {
		en = "Tarot cards of enemies for Realms (LAN) sessions. A drawn card's enemies spawn near the squad but out of sight, ignore the director's spawn limits, and are picked at random or by an in-game vote. Everything is synced to all players' HUD. Edit cards in the Deck (keybind below, or /gt_editor). Move the Draw with the Custom HUD mod. Host needs the mod; clients need it to see the HUD and vote. Spawn distances are measured from the nearest player. The memory guard pauses spawning when the game uses that much memory (the game itself crashes at 1024 MB).",
	},

	mode = { en = "Card selection mode" },
	mode_tarot = { en = "Tarot draw" },
	mode_random = { en = "Random countdown" },
	mode_vote = { en = "Votes (legacy)" },
	tarot_cards = { en = "Cards drawn" },
	tarot_seconds = { en = "Seconds before the pick" },
	tarot_default_cooldown = { en = "Default card cooldown" },
	cooldown_reset_pct = { en = "Reset cooldowns at" },
	nightmare_repeat = { en = "Nightmare can repeat" },

	group_timing = { en = "Timing and voting" },
	initial_delay = { en = "First card draw delay" },
	interval_min = { en = "Min time between draws" },
	interval_max = { en = "Max time between draws" },
	vote_duration = { en = "Final vote window" },
	ballot_size = { en = "Cards drawn for a vote" },
	novote_fallback = { en = "If nobody votes" },
	fallback_random = { en = "Pick a card at random" },
	fallback_skip = { en = "Skip this card" },

	group_spawn = { en = "Spawning" },
	max_per_wave = { en = "Max enemies per card" },
	max_alive = { en = "Max card enemies alive" },
	heap_guard_mb = { en = "Memory guard (pause above)" },
	unit_megabytes = { en = "MB" },
	min_distance = { en = "Min spawn distance" },
	max_distance = { en = "Max spawn distance" },
	monster_min_distance = { en = "Monster min spawn distance" },
	monster_max_distance = { en = "Monster max spawn distance" },

	group_multipliers = { en = "Enemy number multipliers (apply to every card)" },
	mult_normal = { en = "Normal and elite enemies" },
	mult_boss = { en = "Bosses (incl. twins)" },
	mult_special = { en = "Specials (hounds...)" },
	unit_percent = { en = "pct" },

	group_controls = { en = "Keys" },
	open_editor_bind = { en = "Open the Deck (card editor)" },
	vote_1_bind = { en = "Vote for option 1" },
	vote_2_bind = { en = "Vote for option 2" },
	vote_3_bind = { en = "Vote for option 3" },
	vote_4_bind = { en = "Vote for option 4" },
	vote_5_bind = { en = "Vote for option 5" },

	group_hud = { en = "HUD and debug" },
	hud_enabled = { en = "Show the Draw" },
	hud_last_transparency = { en = "Last Card transparency" },
	card_share_icons = { en = "Show Share Card sigils" },
	card_sounds = { en = "Play card sounds (when a card is drawn)" },
	nightmare_dread = { en = "Nightmare's dread on screen" },
	card_auras = { en = "Card effects on the HUD" },
	card_auras_description = { en = "Every suit's own living effect on its cards in the hand (the Draw) and in the last card window: flames on Rage, bubbles and flies on Plague, bullets on Volley, feathers on Grace... They grow with the card's threat; a Murmur card of threat 5 or 6 murmurs its name." },
	deck_card_effects = { en = "Card effects in the Deck" },
	deck_card_effects_description = { en = "Every living effect on the cards of the editor: the Deck's cards, the card you are editing and the Face tab's previews (the suits' effects, the heartbeat of Heresy, the fog of Nightmare, the shine of a sixth diamond, the murmur of a Murmur card's letters). Off: the cards stand still." },
	nightmare_fog_strength = { en = "Nightmare darkness" },
	dream_sky_strength = { en = "Dream's sky strength" },
	dream_sky_strength_description = { en = "How bright Dream's sky is when a Dream card is drawn: the light, the clouds and the rainbow over the screen. 100 = as made, 150 = half again as bright, 0 = none." },
	mode_description = { en = "How the next card is chosen. Tarot draw: a hand of cards is dealt and one of them is picked after a few seconds. Random countdown: a random card is drawn when the timer runs out. Votes (legacy): players vote between cards with the vote keys. Host setting." },
	group_timing_description = { en = "When cards are drawn and how they are chosen. Host settings." },
	tarot_cards_description = { en = "How many cards are dealt into each hand (1 to 5). Host setting." },
	tarot_seconds_description = { en = "How long a hand stays on the table before one of its cards is picked. Host setting." },
	tarot_default_cooldown_description = { en = "How long a card rests after it is drawn, when it has no cooldown of its own. Host setting." },
	cooldown_reset_pct_description = { en = "When this percent of the cards in the draw (or more) are cooling down, every card's cooldown ends at once, so a short time between draws never leaves too few cards to deal. 0 = never. Host setting." },
	nightmare_repeat_description = { en = "Off: once one Nightmare card is drawn, no other Nightmare card is drawn until the next mission. On: Nightmare cards come back like any other card, after their cooldown. Host setting." },
	initial_delay_description = { en = "Seconds added to the wait before the first card draw of a mission. Host setting." },
	interval_random_description = { en = "On: the time between card draws is random, between the minimum and the maximum. Off: always the minimum. Host setting." },
	pool_all_players_description = { en = "On: the cards in the draw of every player who has the mod join the draw, not only the host's. Identical cards count once. Host setting." },
	anti_snowball_description = { en = "When a player dies the countdown to the next card (and every fixed timer) is pushed back, so the team gets a breather. Host setting." },
	anti_snowball_delay_description = { en = "How many seconds a death pushes the next card back while Anti-snowballing is on. Host setting." },
	interval_min_description = { en = "The shortest wait between two card draws, in seconds (the fixed wait when the time is not random). Host setting." },
	interval_max_description = { en = "The longest wait between two card draws, in seconds. Only used while the time is random. Host setting." },
	vote_duration_description = { en = "Votes mode: how many seconds before a card is drawn its vote opens and is highlighted. Never longer than the wait. Host setting." },
	ballot_size_description = { en = "Votes mode: how many different cards players can vote between (2 to 5). Host setting." },
	novote_fallback_description = { en = "Votes mode: what happens when nobody votes: a card is picked at random, or the card is skipped. Host setting." },
	group_spawn_description = { en = "Limits for the cards' enemies: how many, how far from the players, and a memory guard. Host settings." },
	max_per_wave_description = { en = "The most enemies one card spawns; a bigger card is cut to this. Host setting." },
	max_alive_description = { en = "The most card enemies alive at once; a card waits for room above this. Host setting." },
	heap_guard_mb_description = { en = "Spawning pauses while the game's Lua memory is above this many megabytes, and goes on when it drops. Lower it if big cards make the game stutter or crash. Host setting." },
	min_distance_description = { en = "The closest a card's enemies spawn to the players, in meters. Host setting." },
	max_distance_description = { en = "The farthest a card's enemies spawn from the players, in meters. Host setting." },
	monster_min_distance_description = { en = "The closest a card's monsters (Beast of Nurgle, Chaos Spawn, Plague Ogryn...) spawn to the players, in meters. Host setting." },
	monster_max_distance_description = { en = "The farthest a card's monsters spawn from the players, in meters. Host setting." },
	group_multipliers_description = { en = "Scale the number of enemies of every card by kind. 100 = as written on the card. Host settings." },
	mult_normal_description = { en = "Percent of the normal and elite enemies of every card (200 = twice as many, 50 = half). Host setting." },
	mult_boss_description = { en = "Percent of the bosses of every card, the twins included. Host setting." },
	mult_special_description = { en = "Percent of the specials of every card (hounds, trappers, bursters...). Host setting." },
	group_controls_description = { en = "Keys for the editor and for voting." },
	open_editor_bind_description = { en = "Opens the Deck, where you make, change and share cards." },
	vote_1_bind_description = { en = "Votes mode: votes for the first card of the ballot." },
	vote_2_bind_description = { en = "Votes mode: votes for the second card of the ballot." },
	vote_3_bind_description = { en = "Votes mode: votes for the third card of the ballot." },
	vote_4_bind_description = { en = "Votes mode: votes for the fourth card of the ballot." },
	vote_5_bind_description = { en = "Votes mode: votes for the fifth card of the ballot." },
	group_spread_description = { en = "How the Draw (the hand of cards on your screen) looks and moves. Your screen only." },
	tarot_scale_description = { en = "The size of the Draw on your screen." },
	tarot_opacity_description = { en = "How solid the Draw is (100 = solid, lower is more see-through)." },
	tarot_timer_below_description = { en = "Shows the hand's countdown under the cards instead of above them." },
	tarot_hide_icon_description = { en = "Hides the suit's symbol in the corner of the Draw's cards." },
	tarot_ping_description = { en = "In the editor, a card's frame flashes on the Deck when it comes back from its cooldown." },
	tarot_font_description = { en = "The font of the card names on the Draw and in the last card window." },
	tarot_roulette_description = { en = "How long the highlight runs over the hand before it stops on the picked card." },
	tarot_winner_description = { en = "How long the picked card stays shown, with its whisper, before the Draw goes away." },
	tarot_eye_open_description = { en = "How long the eye takes to open over the picked card." },
	tarot_eye_size_description = { en = "The size of the eye that opens over the picked card." },
	tarot_rot_short_description = { en = "How long the rot of a drawn card takes to spread when its cooldown is the shortest (30 seconds)." },
	tarot_rot_long_description = { en = "How long the rot of a drawn card takes to spread when its cooldown is the longest." },
	tarot_longest_description = { en = "The cooldown counted as the longest: the rot's strength and length are scaled between 30 seconds and this." },
	group_hud_description = { en = "The HUD windows and their effects, the editor's colours and debug logging." },
	hud_enabled_description = { en = "Shows the Draw on your screen: the hand of cards, its countdown and the vote." },
	card_share_icons_description = { en = "Shows the Share Card sigil in the corner of the Deck's cards; click it to copy a card's text for a friend." },
	card_sounds_description = { en = "Plays the suit's sound when a card is drawn." },
	hud_show_percent_description = { en = "Shows each card's chance (percent) next to its name in the Draw." },
	colour_enemies_description = { en = "Colours enemy names in the editor by kind (special, boss, elite...)." },
	colour_spidey_description = { en = "Takes an enemy's colour from your Spidey Sense settings when that mod is installed." },
	debug_description = { en = "Writes the mod's decisions (draws, spawns, refusals) to the game's log, to help find a problem." },
	hud_last_transparency_description = { en = "How see-through the last card window is (0 = solid, 100 = invisible)." },
	nightmare_fog_strength_description = { en = "How dark the Nightmare gets: the black fog over its card and over the screen when it is drawn. 70 = the default darkness, 100 = almost black, 0 = none." },
	hud_avoid_boss_bars = { en = "Move the Draw HUD below boss bars" },
	hud_boss_bars_below = { en = "...or keep it on top and move the boss bars below it" },
	hud_boss_bars_below_description = { en = "Swaps the two while a boss is up: the Draw HUD stays at the top and the boss health bars are moved below it, back to their own place when the boss is gone." },
	hud_boss_opacity = { en = "Draw HUD opacity while a boss is up" },
	hud_boss_opacity_description = { en = "While a boss health bar is shown, the Draw HUD fades to this opacity so it hides less of the fight (100 = no change)." },
	hud_avoid_boss_bars_description = { en = "While a boss health bar is shown at the top of the screen, the Draw HUD slides down below it, and back up when the boss is dead. Only when the Draw HUD is where the bars are." },
	nightmare_dread_description = { en = "When a Nightmare card is drawn, a black fog darkens the whole screen for a few seconds (still see-through) while its sound plays." },
	suit_desc_prayer = { en = "Teal devotion: strength and aid for the faithful." },
	suit_desc_miracle = { en = "Holy gold: healing in the darkest hour." },
	suit_desc_grace = { en = "Angel white: renewed strength for the party." },
	suit_desc_dream = { en = "DREAM: Nightmare's opposite, the bright sleep after the dark. Twilight lavender, a sky-blue accent, a frame that turns through a rainbow, clouds in every colour on its face; when it is drawn the sky opens over the screen. A cloud with a star." },
	suit_desc_faith = { en = "The Order of the Sacred Rose: devotion under fire, and the wonders it earns. Wine-rose card, sacred rose pink, a rose in a ring." },
	hud_last_card = { en = "Last card" },
	hud_last_card_description = { en = "Show the window of the last card: the card whose enemies went out last, with how long ago. It stays until the next card goes out. Move it with Custom HUD." },
	hud_last_ago = { en = "%s ago" },
	hud_show_percent = { en = "Show chances in the vote" },
	colour_enemies = { en = "Colour enemy names" },
	colour_spidey = { en = "Use Spidey Sense colours" },
	interval_random = { en = "Random time between draws" },
	pool_all_players = { en = "Draw cards from all players in the lobby" },
	anti_snowball = { en = "Anti-snowballing" },
	anti_snowball_delay = { en = "Delay when someone dies" },
	debug = { en = "Debug logging" },

	unit_seconds = { en = "s" },
	unit_meters = { en = "m" },
	unit_minutes = { en = "min" },
	unit_pixels = { en = "px" },

	-- The Spread: the timeline of the reveal, on your own screen only
	group_spread = { en = "The Draw (your screen)" },
	tarot_scale = { en = "HUD size" },
	tarot_opacity = { en = "HUD opacity" },
	tarot_timer_below = { en = "Timer below the cards" },
	tarot_hide_icon = { en = "Hide the corner symbol" },
	tarot_ping = { en = "Ping when a card is back" },
	tarot_font = { en = "Font of the cards" },
	font_novarese_bold = { en = "Novarese Bold" },
	font_novarese = { en = "Novarese" },
	font_friz = { en = "Friz Quadrata" },
	font_proxima = { en = "Proxima Nova" },
	font_rexlia = { en = "Rexlia" },
	font_machine = { en = "Machine" },
	tarot_roulette = { en = "Roulette" },
	tarot_winner = { en = "Winner shown" },
	tarot_eye_open = { en = "Eye opening" },
	tarot_eye_size = { en = "Eye size" },
	tarot_rot_short = { en = "Rot, shortest cooldown" },
	tarot_rot_long = { en = "Rot, longest cooldown" },
	tarot_longest = { en = "Longest cooldown" },

	-- HUD panel (always localized with arguments, so "%%" is a literal percent sign)
	hud_wave_in = { en = "Next card in %s" },
	hud_wave_in_vote = { en = "Next card in %s. Vote: %s" },
	hud_vote_now = { en = "VOTE NOW: %s left. %s" },
	hud_incoming = { en = "CARD DRAWN: %s" },
	hud_paused = { en = "(PAUSED)" },
	hud_card_in = { en = "Card revealed in" },
	hud_next_card = { en = "Next card in" },
	hud_card_drawn = { en = "The card is drawn" },
	hud_card_drawn_special = { en = "Heresy is drawn" },
	hud_empty_tarot = { en = "No card is in the draw (open the Deck)" },
	hud_all_cooling = { en = "Every card is resting" },
	msg_anti_snowball = { en = "GrandfathersTarot: a player died, the card timers are delayed by %s seconds." },
	hud_no_votes = { en = "No votes, card skipped" },
	hud_empty = { en = "Cards: nothing to draw (open the Deck). Cards on fixed timers still run." },
	hud_line = { en = "%s  %s (%s%%)" },
	hud_line_votes = { en = "%s  %s (%s%%)  [%d]" },
	hud_line_plain = { en = "%s  %s" },
	hud_line_votes_plain = { en = "%s  %s  [%d]" },
	vote_cast = { en = "Voted %d: %s" },

	-- Wave editor
	view_title = { en = "The Grandfather's Tarot" },
	-- the screens of one card: its enemies (and the picker, Mods and Custom) and its face
	view_title_cauldron = { en = "The Grandfather's Workshop" },
	view_title_mirror = { en = "The Grandfather's Mirror" },
	-- the Cauldron's shelf, stage and quick face (docs/08)
	tab_enemies = { en = "Enemies" },
	shelf_title = { en = "Add to this card" },
	shelf_hint = { en = "Click to add one. The card follows." },
	faction_adds = { en = "Adds:" },
	faction_dreg = { en = "Dreg" },
	faction_scab = { en = "Scab" },
	band_fodder = { en = "Fodder" },
	band_elite = { en = "Elites" },
	band_special = { en = "Specials" },
	band_boss = { en = "Bosses" },
	spawn_label = { en = "How it spawns" },
	stage_caption = { en = "The card, as the Deck draws it" },
	stage_stats = { en = "Threat %d  \194\183  %d enemies  \194\183  %s percent of the draw" },
	stage_stats_off = { en = "Out of the draw: it will not be dealt" },
	stage_stats_effect = { en = "Threat %d  \194\183  %d effect  \194\183  %s percent of the draw" },
	stage_stats_effects = { en = "Threat %d  \194\183  %d effects  \194\183  %s percent of the draw" },
	btn_preview_cooldown = { en = "Preview cooldown" },
	btn_quickface = { en = "Whisper and cooldown" },
	quick_label = { en = "Face" },
	lbl_threat = { en = "Threat" },
	msg_max_groups = { en = "GrandfathersTarot: a card holds at most 12 groups of enemies." },
	view_desc_list = {
		en = "Every card that can be drawn. Click a card to put it in or out of the draw; Edit opens it. Only the host's settings are used in a session.",
	},
	deck_count = { en = "%d in the draw" },
	deck_caption = { en = "Click a card to switch it, its pips for its chance, right click to edit, hold it and drop it on another to swap them" },
	sort_label = { en = "Sort by" },
	sort_threat = { en = "Threat" },
	sort_rarity = { en = "Rarity" },
	sort_enemies = { en = "Enemies" },
	sort_face = { en = "Face" },
	tile_pip_hover = { en = "%s: chance %d of 10" },
	-- custom mods of an enemy group (the "Custom" button beside "Mods")
	btn_tune = { en = "Custom" },
	btn_tune_reset = { en = "Reset" },
	col_percent = { en = "Percent" },
	view_desc_tune = { en = "Custom mods of %s: in percent of the normal value, 100 = unchanged. They are applied to every enemy of this group when it spawns." },
	bottom_tune_title = { en = "Custom mods: %s" },
	popup_tune_title = { en = "%s of %s, in percent" },
	popup_tune_hint = { en = "From %d to %d. 100 = unchanged." },
	tune_health = { en = "Health" },
	tune_damage = { en = "Damage dealt" },
	tune_burn = { en = "On Fire damage" },
	tune_burn_info = { en = "How much the On Fire burn hurts the players it sets on fire: 50 = half. %d to %d." },
	mod_fire_damage_info = { en = "Sets players next to it on fire. Burn damage, 0 to 300:" },
	mod_fire_damage_title = { en = "On Fire damage, in percent (0 to 300, 35 by default, 100 = the game's)" },
	tune_damage_info = { en = "How hard its attacks and shots hit: 200 = twice the damage (a sniper's shot too). %d to %d." },
	tune_health_info = { en = "Maximum health. 200 = twice as much. %d to %d." },
	tune_size = { en = "Size" },
	tune_size_info = { en = "Model size, %d to %d. A burster's blast grows with it. Others see it only if they have this mod. Hit areas may not grow." },
	tune_speed = { en = "Run speed" },
	tune_speed_info = { en = "How fast it walks and runs after you. %d to %d." },
	tune_gap = { en = "Time between attacks" },
	tune_gap_info = { en = "How long it waits before it can attack again: 50 = half the wait, 200 = twice as long. Chains keep every hit. %d to %d." },
	tune_fire = { en = "Gunner fire rate" },
	tune_fire_info = { en = "Time between two shots of shooters and gunners. %d to %d." },
	tune_burst = { en = "Shots per burst" },
	tune_burst_info = { en = "Shots in one burst of rifles and gunners (not sniper, plasma, shotgun). %d to %d." },
	tune_mass = { en = "Hit mass" },
	tune_explosion = { en = "Explosion damage taken" },
	tune_explosion_info = { en = "Share of explosion damage it takes: 50 = half, 0 = none. %d to %d." },
	tune_dot = { en = "Damage over time taken" },
	tune_dot_info = { en = "Share of burning, toxin and bleeding damage it takes: 50 = half, 0 = none. %d to %d." },
	tune_mass_info = { en = "How much of a swing it soaks up: more = fewer enemies cut per swing. %d to %d." },
	tile_in = { en = "In the draw" },
	tile_off = { en = "Out of the draw" },
	tile_cooling = { en = "Back in" },
	tile_ready = { en = "Ready" },
	tile_edit = { en = "Edit" },
	tile_cd = { en = "Cooldown" },
	tile_cd_every = { en = "Every" },
	tile_rare = { en = "rare" },
	tile_repeats = { en = "and it repeats" },
	tile_more = { en = "+%d more" },
	tile_no_enemies = { en = "No enemies yet" },
	tile_blank_title = { en = "Name it" },
	tile_blank_hint = { en = "Pick a suit and add enemies. The threat is worked out for you." },
	view_desc_detail = { en = "Editing: %s" },
	view_desc_picker = { en = "Pick an enemy to add to: %s" },
	col_on = { en = "On" },
	col_wave = { en = "Card" },
	col_composition = { en = "Composition" },
	col_chance = { en = "Chance" },
	btn_keep_pick_on = { en = "Random groups: one roll per draw" },
	btn_keep_pick_off = { en = "Random groups: a roll for every unit" },
	col_share = { en = "Share" },
	col_enemy = { en = "Enemy" },
	col_count = { en = "Brood" },
	col_id = { en = "Breed id" },
	bottom_list_title = { en = "The two numbers are the time between cards. The blank card makes a card of your own." },
	bottom_detail_title = { en = "%s: %d enemies in total" },
	-- the "?" tooltip (ui/help_text.lua reads its markup: "# " a title, "## " a heading, "- " a bullet, *lit words*)
	help_title = { en = "How this screen works" },
	help_footer = { en = "Click the ? to keep this open" },
	help_footer_pinned = { en = "Click the ? again to close" },
	hint_list = { en = "# The Deck\nEvery card that can be dealt. Start typing to search it.\n## Cards\n- *Click* a card to put it in or out of the draw (a card out of the draw is dimmed).\n- *Edit*, in a card's corner, opens it: its enemies, chance, cooldown and face.\n- The ten pips are its chance, 1 to 10. Hold the *-* or *+* of its cooldown to keep stepping.\n- The strip at the top shows how likely each card is to be dealt, among the cards that are not resting.\n- The blank card makes a card of your own.\n## The whole deck\n- *Deck presets* keeps whole decks in five slots.\n- *Delete* (inside a card) hides any card, the default ones too. *Restore defaults* brings them back and undoes every other change. *Delete all* deletes every card (it warns twice).\n- The two numbers at the bottom are the time between cards. *More options* has the rest of the timing and display settings." },
	view_desc_mods = { en = "Modifiers for: %s" },
	col_modifier = { en = "Modifier" },
	col_effect = { en = "What it does" },
	btn_mods = { en = "Mods" },
	btn_dogs = { en = "Dogs" },
	btn_shield = { en = "Shield" },
	tune_boss = { en = "Boss bar" },
	tune_cancel = { en = "Attack cancel chance" },
	tune_cancel_info = { en = "The chance that an attack of one hit (a Pox Hound's pounce too) stops before it lands, a feint. 0 = never. %d to %d." },
	tune_spray = { en = "Spray cut chance" },
	tune_spray_info = { en = "Beast of Nurgle and Flamers: the chance that a spray stops part way (a quarter to three quarters through). 0 = never. %d to %d." },
	tune_net = { en = "Net feint chance" },
	tune_net_info = { en = "Trappers: the chance he stops aiming before he fires. He keeps his net (no reload) and can aim again after the Net feint pause. %d to %d." },
	tune_pause = { en = "Feint pause" },
	tune_pause_info = { en = "Trappers and Pox Hounds: after a feint, the wait before the next net or pounce. Seconds, 0 to 15 (1.5 by default)." },
	popup_tune_seconds_hint = { en = "Seconds, %s to %s (halves and tenths too, like 2.5)." },
	tune_combo = { en = "Random combo end" },
	tune_combo_info = { en = "An attack of several hits (the Plague Ogryn's three-hit combo) stops after a random one of them: the first, the second or the last." },
	tune_boss_name = { en = "Boss name" },
	tune_boss_colour = { en = "Boss bar colour" },
	tune_boss_colour_info = { en = "The colour of its boss bar: %s. - and + step through the colours; click the name to type a colour code. A Monster's or a Captain's own bar takes it too." },
	popup_boss_colour_title = { en = "Boss bar colour: %s" },
	popup_boss_colour_hint = { en = "A colour code like ff7a1a (red green blue, two digits each). Empty: the game's red." },
	tune_boss_name_info = { en = "The name in the boss bar. Empty: the enemy's own name. Used while Boss bar is on, and always by an enemy the game shows as a boss (a Monster, a Captain)." },
	tune_boss_name_set = { en = "Shown in the boss bar as: %s" },
	btn_boss_name_edit = { en = "Edit" },
	popup_boss_name_title = { en = "Boss name: %s" },
	popup_boss_name_hint = { en = "Up to 30 letters, digits, spaces and ' - . ! ? Empty: the enemy's own name." },
	tune_boss_info = { en = "Shows these enemies' name and health in the boss bar at the top of the screen, like a Monster or a Captain." },
	btn_leaves_1 = { en = "1 kill" },
	btn_leaves_2 = { en = "2 kills" },
	btn_leaves_3 = { en = "3 kills" },
	btn_leaves_all = { en = "All" },
	note_havoc_only = { en = "(Havoc missions only)" },
	hint_mods = { en = "# Modifiers\nConditions forced onto this group, even when the mission did not bring them (Purple or Enraged on three Crushers, say).\n- Tick a condition to add it. It is put on right after the enemies spawn.\n- Their looks and effects are the game's own.\n- In the text editor they go in brackets: *3 crushers[enraged+garden]*." },
	-- Settings screen (timing, voting, display)
	btn_settings = { en = "More options" },
	btn_default = { en = "Restore defaults" },
	btn_delete_all = { en = "Delete all" },
	btn_delete_all_sure = { en = "Delete all?" },
	btn_delete_all_last = { en = "Last warning!" },
	msg_delete_all_warn = { en = "GrandfathersTarot: Delete all removes EVERY card of your deck, the default ones and your own. Click it again to go on." },
	msg_delete_all_last = { en = "GrandfathersTarot: last warning. One more click deletes every card. Undo last load on the Deck presets screen brings them back." },
	msg_delete_all_done = { en = "GrandfathersTarot: every card is deleted. Undo last load (Deck presets) brings them back, Restore defaults gives the default deck." },
	bottom_list_deleted = { en = "%s default cards are deleted. Restore defaults brings them back." },
	extra_not_random = { en = "(not used: random is off)" },
	msg_defaults_restored = { en = "GrandfathersTarot: every card is back to the defaults (Undo last load on the Deck presets screen restores your previous cards)." },
	help_detail = { en = "# Editing a card\nThe card on the right follows every change.\n## Enemies\n- *Click* an enemy on the shelf to add it. The *Dreg / Scab* switch chooses which kind.\n- A row's *-* and *+* change its brood: how many of that enemy.\n- *Right click* a row to change its enemy and keep its count and modifiers.\n- Some rows have a toggle at their right. *Dogs* (a Packmaster): dark, he comes alone. *Shield* (a Captain or a Twin): dark, no void shield. A Daemonhost's *kills*: how many players die before it leaves (1, 2, 3 or All).\n- *Mods* adds Havoc-style conditions. *Custom* changes health, size, speed, attack speed, fire rate, burst and hit mass.\n- A small diamond beside a name: its group has a colour experiment.\n## The card\n- Under the card: its suit, its threat and its chance. The whisper and the cooldown are on the *Face* tab.\n- Hold a cooldown's *-* or *+* to keep stepping.\n## How it spawns\n- Spread, repeats, and its own minimum and maximum spawn distance.\n- A *fixed timer* ignores the chance: the card spawns every N seconds.\n## Sharing\n- *Share Card* gives you its text. Paste a friend's card over it to take theirs." },
	help_picker = { en = "# Adding an enemy\n- *Click* an enemy to add it. Just start typing to search.\n- The button beside Search chooses whether you stay here after adding, to add several in a row, or go back to the card.\n- *Random group* gathers several enemies into one group: each spawn takes one of them.\n- Opened with a *right click* on a row: the enemy you pick replaces that row's enemy and keeps the rest." },
	help_preset_view = { en = "# A preset slot\n- *Load this setup* replaces *all* your cards with the ones stored here (an empty slot loads an empty deck: every card deleted).\n- *Save current cards here* stores what you have now.\n- *Export* gives you text to send to a friend. *Import* pastes theirs into this slot.\n- *Undo last load* brings your previous cards back, once." },
	btn_delete = { en = "Delete" },
	btn_create = { en = "Create" },
	btn_reset = { en = "Reset" },
	btn_sure = { en = "Sure?" },
	col_setting = { en = "Setting" },
	col_what_it_does = { en = "What it does" },
	col_value = { en = "Value" },
	view_desc_settings = { en = "More options: timing, voting and display. Click a row to change it. The same options are in the mod's options menu. Timing and voting are host settings." },
	hint_settings = { en = "# More options\nTiming, voting and display. Click a row to change it; the same options are in the mod's options menu.\n- Cards arrive after a time between the minimum and the maximum, or after exactly the minimum when the time is not random.\n- The names and chances show from the start of the wait; the vote is lit in its final window.\n- Timing and voting are host settings." },
	set_mode = { en = "Players vote on the next card" },
	set_mode_info = { en = "On: the old vote mode, players pick between cards with the vote keys. Off: the Tarot draw. The Random countdown is chosen in the mod options. Host setting." },
	set_interval_random = { en = "Random time between draws" },
	set_interval_random_info = { en = "On: a random time between the minimum and maximum below. Off: always the same time, the minimum. Host setting." },
	set_interval_min = { en = "Minimum time between draws" },
	set_interval_min_info = { en = "Seconds. The shortest wait until the next card draw. Host setting." },
	set_interval_fixed = { en = "Time between draws" },
	set_interval_fixed_info = { en = "Seconds. Every card is drawn after exactly this long. Host setting." },
	set_interval_max = { en = "Maximum time between draws" },
	set_interval_max_info = { en = "Seconds. The longest wait. Only used while the time is random. Host setting." },
	set_initial_delay = { en = "First card draw delay" },
	set_initial_delay_info = { en = "Seconds added to the wait before the first card draw of a mission. Host setting." },
	set_vote_duration = { en = "Card names shown (vote window)" },
	set_vote_duration_info = { en = "Seconds before a card is drawn that its vote is open and highlighted. Never longer than the wait. Host setting." },
	set_ballot_size = { en = "Cards drawn for a vote" },
	set_ballot_size_info = { en = "How many different cards players can vote between (2 to 5). Host setting." },
	set_pool_all_players = { en = "Draw cards from all players in the lobby" },
	set_pool_all_players_info = { en = "On: the enabled cards of every player with the mod join the draw, not only the host's. Identical cards count once. Host setting." },
	set_hud_show_percent = { en = "Show chances in the vote" },
	set_hud_show_percent_info = { en = "Your screen only: show each card's chance (percent) next to its name in the Draw." },
	set_colour_enemies = { en = "Colour enemy names" },
	set_colour_enemies_info = { en = "Your screen only: colour enemy names in this editor by type (special, boss, elite...)." },
	set_colour_spidey = { en = "Use Spidey Sense colours" },
	set_colour_spidey_info = { en = "Take an enemy's colour from your Spidey Sense settings when that mod is installed." },

	-- Sharing one wave
	btn_share = { en = "Share Card" },
	btn_wimport = { en = "Import card" },
	btn_face = { en = "Face" },
	btn_change = { en = "Change" },
	view_desc_face = { en = "Card face of: %s" },
	bottom_face_title = { en = "%s: suit, threat, whisper and the look of its cooldown. The preview shows the card as the Deck draws it." },
	help_face = { en = "# The card's face\n## Suit\n- Click a suit to give the card its colours and mark. The suggested one follows the enemies: a boss suggests Fateful, specials Blight, a horde of more than 60 without elites Swarm.\n## Threat\n- Worked out from the enemies (1 to 5) unless you set it with *-* and *+*. The line under the rows shows how.\n## Whisper\n- One short line. Empty uses the suit's own.\n## Cooldown\n- How long the card rests after it is drawn. Hold *-* or *+* to keep stepping.\n- The *Automatic* look: the murmur for Murmur cards, rot for the rest.\n## When it is drawn\n- On the right: the card in the hand, as the Draw shows it, and in the last card window." },
	help_tune = { en = "# Custom stats\nEach value is a percent of what the game normally gives this enemy: *100* is unchanged, *150* half again as much, *50* half.\n- Click a number to type it. *Reset* puts it back to 100.\n- Applied right after the enemy spawns, on the host. Health, run speed and hit mass reach every player through the game itself.\n- *Size* is sent to the players who have this mod (the others see the normal size). Only the model grows, maybe not the areas you can hit.\n- *Time between attacks* shortens (below 100) or lengthens (above 100) the wait after a melee attack: the swing itself is not faster, and a chain of hits keeps every hit.\n- *Fire rate* and *burst* work on the attacks that read them: rifles and gunners, not snipers, plasma or shotguns.\n- In the text editor they follow the modifiers in braces: *3 crushers[enraged]{health=150 size=130}*." },
	suit_desc_plague = { en = "Nurgle's blessings: tougher enemies that heal and corrupt. Olive card, bile green, an eye." },
	suit_desc_murmur = { en = "The dark ones: stagger-immune, armoured, hard to see coming. Near-black card, a half moon." },
	suit_desc_rage = { en = "Speed and aggression: fast melee, chargers, hounds. Burnt-brown card, rust, a flame." },
	suit_desc_blight = { en = "Toxic and explosive: gas, bursters, bombers. Mustard-olive card, pus yellow, a drop." },
	suit_desc_swarm = { en = "Numbers over strength: hordes of fodder. Ash-grey olive, quiet on purpose, a cluster of dots." },
	suit_desc_fateful = { en = "Bosses and last stands. Black card, bone text, brass frame, a four-point star." },
	suit_desc_volley = { en = "Ranged fire: gunners, shooters, snipers. Steel-blue card, a crosshair." },
	suit_desc_snare = { en = "Control: trappers, netters, anything that holds you down. Sea-green card, linked rings." },
	suit_desc_brute = { en = "Heavy hitters: ogryns, crushers, bulwarks. Brick-red card, a plated square." },
	suit_desc_heresy = { en = "HERESY: a card apart, the forbidden and the turned. Black and fresh blood, crimson through and through, a broken halo; its glow beats like a heart and it bleeds on every card face." },
	suit_desc_nightmare = { en = "NIGHTMARE: the dark that hunts. Black on black, a horned eye, a light that dies. ONCE PER GAME: when one Nightmare card is played, every Nightmare card leaves the draw until the next mission." },
	suit_desc_warp = { en = "The Daemonhost. Purple card, an eye in a triangle. Suggested for any card that holds one." },
	face_suggested = { en = "(suggested for these enemies)" },
	face_threat = { en = "Threat" },
	face_threat_auto = { en = "Worked out from the enemies, see below. + sets it by hand." },
	face_threat_own = { en = "Set by hand. - down to auto works it out again." },
	face_whisper = { en = "Whisper" },
	face_whisper_suit = { en = "(the suit's own line) %s" },
	face_look = { en = "Cooldown look" },
	look_rot = { en = "Rot and renewal" },
	look_whisper = { en = "The murmur returns" },
	look_vial = { en = "The vial fills" },
	face_look_auto = { en = "Automatic: %s" },
	face_cooldown = { en = "Cooldown" },
	face_cooldown_info = { en = "Seconds the card rests after it is drawn: 30 s steps up to %d minutes (the longest cooldown option)." },
	face_numbers = { en = "Threat %d by the numbers: %d enemies give %d" },
	-- the Mirror (docs/08)
	mirror_suit = { en = "Suit" },
	mirror_suit_hint = { en = "Sets the colours and the corner icon." },
	btn_kind_hostile = { en = "Enemies" },
	btn_kind_ben = { en = "Beneficial" },
	threat_level = { en = "Level %d" },
	threat_level_six = { en = "6 %s" },
	face_level = { en = "Level %d." },
	face_level_six = { en = "Level 6: %s." },
	face_murmur = { en = " Its whisper comes back letter by letter when it is drawn and chosen." },
	look_every_card = { en = "Every card" },
	col_effect = { en = "Effect" },
	col_amount = { en = "Amount" },
	col_players = { en = "Players" },
	fx_shelf_hint = { en = "Click to add an effect, click again to take it off. The card follows." },
	fx_fixed_revive = { en = "1 hogtied, brought back" },
	fx_off_for_now = { en = "off" },
	snd_silence = { en = "Silence" },
	snd_choose = { en = "Choose a sound in the list" },
	snd_add_second = { en = "Add a second sound" },
	snd_remove_second = { en = "Remove 2" },
	snd_search = { en = "Search" },
	snd_search_title = { en = "Search card sounds" },
	popup_drag_hint = { en = "Type to filter the list. Drag this title to move the box; Enter or Esc closes it." },
	snd_volume = { en = "Volume %d" },
	snd_volume_hint = { en = "0 to 100. 0 never plays. Below 100 is an experiment: the game has no volume per sound." },
	snd_button_silent = { en = "Sound: silent" },
	snd_button_one = { en = "Sound: 1 set" },
	snd_button_two = { en = "Sound: 2 in a row" },
	snd_preview = { en = "Preview" },
	view_desc_sounds = { en = "Card sound, played when the card is drawn; its enemies spawn when it ends. Preview plays a row, Select puts it in the open slot (1 or 2); the second plays after the first. Silence clears both." },
	mirror_threat = { en = "Threat" },
	mirror_threat_hint = { en = "Worked out from the enemies. Click a diamond to set it by hand." },
	mirror_whisper = { en = "Whisper" },
	mirror_whisper_hint = { en = "The line in quotes on the card. Empty borrows the suit's own line." },
	mirror_cooldown = { en = "Cooldown" },
	mirror_cooldown_hint = { en = "Seconds the card rests after it is drawn. Steps of 30 s, up to %d minutes." },
	mirror_cooldown_extra = { en = "%d seconds before it can be drawn again" },
	mirror_suggested = { en = "Suggested" },
	hand_caption = { en = "When it is drawn" },
	face_last_sample = { en = "just drawn" },
	btn_whisper_suit = { en = "Use the suit's line" },
	btn_look_auto = { en = "Automatic for this suit" },
	btn_reset_face = { en = "Reset face" },
	look_rot_desc = { en = "Grey, brown, ochre, then the suit's colour." },
	look_whisper_desc = { en = "The whisper comes back letter by letter." },
	look_vial_desc = { en = "Pus rises from the bottom of the card." },
	look_automatic = { en = "Automatic" },
	look_sample = { en = "Do you hear it?" },
	face_elites = { en = ", elites +1" },
	face_specials = { en = ", specials +1" },
	face_boss = { en = ", a boss +2" },
	face_override = { en = "Set by hand to %d." },
	face_suggest = { en = "Suggested suit: %s." },
	popup_whisper_title = { en = "Whisper of %s" },
	popup_whisper_hint = { en = "At most 40 characters. Leave it empty to use the suit's own line." },
	popup_threat_title = { en = "Threat of %s" },
	popup_threat_hint = { en = "0 works it out from the enemies, 1 to 6 sets it by hand; 6 is DESPAIR (APOTHEOSIS on a beneficial card)." },
	popup_share_title = { en = "Share: %s" },
	popup_share_hint_copied = { en = "Copied to your clipboard. To import a friend's card OVER THIS card, paste it here and press OK." },
	popup_share_hint = { en = "Press Ctrl+A then Ctrl+C to copy. To import a friend's card OVER THIS card, paste it here and press OK." },
	popup_wimport_title = { en = "Import a card" },
	popup_wimport_hint = { en = "Paste a friend's card text (Ctrl+V), then OK. It goes into the first free custom slot (%s)." },
	popup_wimport_hint_filled = { en = "Your clipboard holds a card, filled in below. OK imports it into the first free custom slot (%s)." },
	msg_wave_replaced = { en = "Replaced this card with the imported one: %s" },
	msg_wave_imported = { en = "Imported card %s into %s." },
	msg_no_free_slot = { en = "All custom slots are in use. Delete one first, or open a card and use Share to import over it." },

	-- Presets
	btn_presets = { en = "Deck presets" },
	btn_open = { en = "Open" },
	btn_pload = { en = "Load this setup" },
	btn_psave = { en = "Save current cards here" },
	btn_pexport = { en = "Export (copy)" },
	btn_pimport = { en = "Import (paste)" },
	btn_pundo = { en = "Undo last load" },
	btn_pclear = { en = "Clear slot" },
	col_preset = { en = "Preset" },
	col_preset_holds = { en = "What it holds" },
	view_desc_presets = { en = "Five slots for your whole deck. Open a slot to save your current cards into it, load it back, or share it with friends." },
	view_desc_preset = { en = "Preset %s: %s" },
	hint_presets = { en = "# Deck presets\nFive slots, each holding a whole deck: every card you changed, with its enemies, chance, cooldown, spread and repeats.\n- Open a slot to save your deck into it, load it back or share it.\n- Loading replaces *all* your cards. *Undo last load* brings the previous deck back.\n- *Export* gives one line of text to send to a friend, who opens a slot and presses *Import*." },
	preset_slot_empty = { en = "(empty)" },
	preset_slot_empty_long = { en = "Empty slot. Press Save current cards here to store your deck, or Import to paste a friend's preset." },
	preset_slot_info = { en = "%s changed cards: %s" },
	preset_slot_broken = { en = "(damaged, clear it or import again: %s)" },
	preset_all_default = { en = "Everything at the default setup" },
	preset_view_title = { en = "%s changed cards in this preset. Cards not listed load as the defaults." },
	preset_wave_disabled = { en = "(disabled)" },
	preset_saved = { en = "Saved %s: %s changed cards stored." },
	preset_loaded = { en = "Loaded %s (%s changed cards). Undo last load restores your previous cards." },
	preset_undone = { en = "Your previous cards are back." },
	preset_cleared = { en = "Slot cleared." },
	preset_nothing_to_load = { en = "This slot is damaged, nothing to load. Clear it or import again." },
	preset_loaded_blank = { en = "Slot %s is empty: loaded an empty deck (every card deleted). Save current cards here to store a deck in it. Undo last load restores your previous cards." },
	preset_nothing_to_export = { en = "This slot is empty, nothing to export." },
	preset_nothing_to_undo = { en = "Nothing to undo." },
	preset_save_first = { en = "Save your current cards into this slot first, then you can rename it." },
	preset_imported = { en = "Imported %s (%s changed cards)." },
	preset_imported_skipped = { en = "Imported %s (%s changed cards). %s cards were skipped, this version does not know them." },
	preset_undo_name = { en = "Before last load" },
	popup_preset_rename_title = { en = "Rename preset %s" },
	popup_export_title = { en = "Export: %s" },
	popup_export_hint_copied = { en = "Copied to your clipboard. Paste it to a friend (Ctrl+V). They open a slot and press Import (paste)." },
	popup_export_hint = { en = "Could not copy automatically: press Ctrl+A then Ctrl+C in the box, then paste it to a friend." },
	popup_import_title = { en = "Import into slot %s" },
	popup_import_hint = { en = "Paste the preset text here (Ctrl+V), then OK. It replaces whatever is in slot %s." },
	popup_import_hint_filled = { en = "Your clipboard already holds a preset, filled in below. OK imports it into slot %s and replaces what is there." },

	btn_search = { en = "Search enemies" },
	btn_search_active = { en = "Search: %s" },
	btn_deck_search = { en = "Search cards" },
	deck_search_title = { en = "Search the Deck" },
	deck_search_hint = { en = "A card's name, suit, enemy or effect. The Deck shows the cards that match as you type; empty shows them all." },
	btn_stay_on = { en = "Stays here after adding" },
	btn_stay_off = { en = "Back to the card after adding" },
	btn_random_off = { en = "Random group: off" },
	btn_random_on = { en = "Random group: ON" },
	btn_random_done = { en = "Create group (%s)" },
	picker_random_status = { en = "Random group: %s." },
	picker_random_none = { en = "click two or more enemies, then Create group" },
	picker_random_need_two = { en = "Pick at least two enemies for a random group." },
	picker_random_added = { en = "Added a random group of %s enemies." },
	col_cooldown = { en = "Cooldown" },
	picker_added = { en = "Added %s (now %s in this card)." },
	picker_swap = { en = "Changing the enemy of \"%s\": pick the new one (its count, repeats, modifiers, custom mods and colours stay)." },
	popup_search_title = { en = "Search enemies" },
	popup_search_hint = { en = "Type part of a name, alias or type (boss, special, elite, horde). The list filters as you type. Enter keeps it, Esc undoes. (Typing anywhere on this screen opens this box.)" },
	picker_status = { en = "Showing all %s of %s enemies" },
	picker_status_filtered = { en = "Showing %s of %s enemies matching: %s" },
	btn_back = { en = "Back" },
	btn_rename = { en = "Rename" },
	btn_edit_text = { en = "Edit as text" },
	btn_add_enemy = { en = "Search all enemies" },
	btn_enabled_on = { en = "In the draw" },
	btn_enabled_off = { en = "Out of the draw" },
	btn_reset_default = { en = "Reset to default" },
	btn_reset_clear = { en = "Clear this slot" },
	btn_edit = { en = "Edit" },
	btn_remove = { en = "Remove" },
	btn_add = { en = "Add" },
	col_repeat = { en = "Added each repeat" },
	col_same = { en = "Same" },
	lbl_dmin = { en = "Min distance" },
	lbl_dmax = { en = "Max distance" },
	val_auto = { en = "auto" },
	extra_dist_auto = { en = "= %s m" },
	extra_dist_own = { en = "m" },
	lbl_timer = { en = "Fixed timer" },
	val_off = { en = "off" },
	extra_timer_off = { en = "by chance" },
	extra_timer_on = { en = "s: no chance" },
	extra_timer_wave = { en = "not drawn: it runs on its own fixed timer" },
	extra_timer_ignored = { en = "(ignored: fixed timer)" },
	share_timer = { en = "every %s s" },
	popup_timer_title = { en = "Fixed timer of %s in seconds (0 = off and drawn by chance, otherwise at least 5)" },
	popup_dmin_title = { en = "Minimum spawn distance of %s in metres (0 = use the options, up to 200)" },
	popup_dmax_title = { en = "Maximum spawn distance of %s in metres (0 = use the options, up to 200)" },
	lbl_spread = { en = "Spread radius" },
	extra_meters = { en = "m" },
	lbl_repeat_every = { en = "Repeat every" },
	extra_seconds = { en = "seconds" },
	extra_no_repeat = { en = "no repeat" },
	lbl_repeat_for = { en = "Repeat for" },
	extra_seconds_short = { en = "s" },
	popup_rep_title = { en = "Enemies added on every repeat: %s (0 to 60)" },
	popup_spread_title = { en = "Spread radius of %s in metres (0 to 100)" },
	popup_every_title = { en = "Repeat %s every this many seconds (1 to 600)" },
	popup_for_title = { en = "Keep repeating %s for this many seconds (0 to 3600)" },
	lbl_chance = { en = "Chance" },
	lbl_cooldown = { en = "Cooldown" },
	extra_share = { en = "= %s percent of the draw" },
	extra_share_short = { en = "= %s%%" },
	extra_timer_short = { en = "timer card" },
	extra_not_drawn_short = { en = "not drawn" },
	lbl_cooldown_short = { en = "Cooldown" },
	extra_not_drawn = { en = "not drawn (disabled, empty or chance 0)" },
	extra_cooldown = { en = "seconds before it can repeat" },
	row_empty_slot = { en = "(empty slot)" },
	list_range = { en = "%s - %s of %s" },
	msg_need_one_enemy = { en = "GrandfathersTarot: a built-in card needs at least one enemy (use Reset to default to restore it)." },
	popup_chance_title = { en = "Chance of %s (0 to 10)" },
	popup_count_title = { en = "Brood of %s" },
	popup_cooldown_title = { en = "Cooldown of %s in seconds (0 to 3600)" },
	popup_rename_title = { en = "New name for this card" },
	popup_recipe_title = { en = "Edit the enemies as text" },
	popup_recipe_hint = { en = "Example: 5 trappers, 3 crushers[enraged+garden]@2 (+2 on every repeat) or 3 crushers@= (the same 3 again on every repeat). Random pick: 1 plague ogryn|chaos spawn." },
	popup_number_error = { en = "Enter a whole number from %s to %s" },
	popup_hint_number = { en = "Type a number, Enter to confirm, Esc to cancel" },
	popup_hint_text = { en = "Type the text, Enter to confirm, Esc to cancel" },
	popup_ok = { en = "OK" },
	snd_stop_previews = { en = "Stop all sound previews" },
	snd_not_loaded = { en = "%s did not start: the game has not loaded this sound right now (some sounds come only with the item that uses them, like the stimm syringes)." },
	btn_draw_ben_on = { en = "Add beneficial cards to the draw" },
	btn_draw_ben_off = { en = "Remove beneficial cards from the draw" },
	btn_draw_foe_on = { en = "Add enemy cards to the draw" },
	btn_draw_foe_off = { en = "Remove enemy cards from the draw" },
	msg_draw_kind = { en = "%d cards changed." },
	popup_cancel = { en = "Cancel" },
	-- Twins (2026-10-07, merged from SoloPlayPurpleStimms)
	group_twins = { en = "Twins" },
	group_twins_bosses = { en = "Twins: bosses" },
	group_twins_enemies = { en = "Twins: enemies" },
	group_twins_reset = { en = "Twins: reset" },
	tw_reset_defaults = { en = "Reset Twins to default" },
	tw_reset_defaults_button = { en = "Hold to reset" },
	tw_reset_defaults_tooltip = { en = "Hold the button to put every Twins setting back to the game's own defaults: the chance, the split enemies and the spawned-enemy rule of every boss and enemy, the stimm colour, the smoke, Hide from guests, Don't re-stim, the loop check and the boss switches. Nothing else of the mod is touched (the cards' own Twins rows neither)." },
	tw_reset_done = { en = "Twins: every setting is back to the game's defaults." },
	tw_guest_safe = { en = "Hide from guests" },
	tw_guest_safe_tooltip = { en = "On: players who join your game without this mod see the game's own \"Contaminated Stimms\" condition instead of Twins, so nothing errors for them (your own HUD shows that name too). Off: the condition keeps its real name everywhere, but players without this mod get an error on the Havoc conditions text and icon. Applies to missions started after you change it." },
	tw_no_restim = { en = "Don't re-stim when purple" },
	tw_no_restim_tooltip = { en = "On: an enemy that already carries the purple stimm (a twin that spawned with it) does not use a stim again: no second stim animation. Off: like the game, it may stim again (the buff does not stack, so nothing changes except the animation)." },
	tw_loop_check = { en = "Check infinite spawn loops" },
	tw_loop_check_tooltip = { en = "On: a split rule that would make an endless chain (an enemy that splits into something that eventually splits back into it) is detected: you get a warning when you edit it, and the enemy that would close the loop is spawned without the purple stimm, so the chain ends. Off: nothing is checked and such a chain spawns forever (a queue limit still stops it flooding the game). The cards' own Twins rows have their own limit: Generations." },
	tw_color_custom = { en = "Custom stimm colour" },
	tw_color_custom_tooltip = { en = "Recolour the purple glow of stimmed enemies with the red, green and blue sliders below (0-255). Off keeps the game's purple (191, 0, 191). Applies to enemies stimmed from now on. Every player sets this for themselves; it only changes what you see. The split smoke can only be switched on or off, not recoloured." },
	tw_color_r = { en = "Stimm red" },
	tw_color_g = { en = "Stimm green" },
	tw_color_b = { en = "Stimm blue" },
	tw_color_channel_tooltip = { en = "0-255. Only used while Custom stimm colour is on." },
	tw_smoke_enabled = { en = "Split smoke" },
	tw_smoke_enabled_tooltip = { en = "The purple smoke burst when a stimmed enemy splits. Off: no smoke (the split itself still happens). Every player sets this for themselves. Try it with /gt_twins_smoke." },
	tw_smoke_sound = { en = "Split smoke sound" },
	tw_smoke_sound_tooltip = { en = "The gas sound that plays with the smoke burst. Off: the split is silent. Every player sets this for themselves." },
	tw_smoke_command = { en = "GrandfathersTarot: play the Twins split burst in front of you with your smoke settings (to try them)" },
	tw_bosses_enabled = { en = "Affect bosses" },
	tw_bosses_enabled_tooltip = { en = "Master switch of the Twins condition. Off: no boss ever gets the purple stimm, whatever the per-boss settings below say." },
	tw_bosses_chance = { en = "Boss stimm chance" },
	tw_bosses_chance_tooltip = { en = "Chance that a spawned boss gets the purple stimm under the Twins condition. It is multiplied with the per-boss chance below (50%% here and 50%% there = 25%%)." },
	tw_boss_selector = { en = "Boss" },
	tw_boss_selector_tooltip = { en = "Pick a boss; the settings below apply to that boss only (under the Twins condition)." },
	tw_enemy_selector = { en = "Enemy" },
	tw_enemy_selector_tooltip = { en = "Pick an enemy; the settings below apply to that enemy only (under the Twins condition). Enemies marked [!] have no stim animation." },
	tw_boss_enabled = { en = "Gets the purple stimm" },
	tw_enemy_enabled = { en = "Gets the purple stimm" },
	tw_enabled_tooltip = { en = "Under the Twins condition, whether this one gets the purple stimm at all." },
	tw_boss_chance = { en = "Chance" },
	tw_boss_chance_tooltip = { en = "Chance this boss gets the purple stimm when it spawns. Captains have a stim animation and use it instead, with this chance." },
	tw_enemy_chance = { en = "Chance" },
	tw_enemy_chance_tooltip = { en = "Enemies with a stim animation: the chance that they use the stim when they aggro. Enemies marked [!] have none: the chance that they spawn with the purple stimm already applied." },
	tw_boss_twin1 = { en = "Twin 1 (spawned on death)" },
	tw_boss_twin2 = { en = "Twin 2 (spawned on death)" },
	tw_enemy_twin1 = { en = "Twin 1 (spawned on death)" },
	tw_enemy_twin2 = { en = "Twin 2 (spawned on death)" },
	tw_boss_twin_tooltip = { en = "Enemy spawned when this boss dies with the purple stimm. \"Default\" uses the game's own split rule, \"None\" spawns nothing. Spawning monsters is not something the game normally does here, so expect the odd oddity." },
	tw_enemy_twin_tooltip = { en = "Enemy spawned when this enemy dies with the purple stimm. \"Default\" uses the game's own split rule, \"None\" spawns nothing." },
	tw_boss_twins_buff = { en = "Twins get the stimm" },
	tw_enemy_twins_buff = { en = "Twins get the stimm" },
	tw_twins_buff_tooltip = { en = "Default: like the game, a spawned twin only carries the purple stimm if it can split again. Always: every twin carries it. Never: none does." },
	tw_twin_default = { en = "Default" },
	tw_twin_none = { en = "None" },
	tw_twins_buff_default = { en = "Default (only if they split again)" },
	tw_twins_buff_always = { en = "Always" },
	tw_twins_buff_never = { en = "Never" },
	tw_warning_spawn_loop_prevented = { en = "Twins spawn loop: %s. The enemy that would close the loop is spawned without the purple stimm, so the chain ends." },
	tw_warning_spawn_loop_unchecked = { en = "Twins spawn loop: %s. Check infinite spawn loops is off, so this spawns enemies forever." },
	tw_warning_self_split_one_prevented = { en = "Twins spawn loop: %s splits into %s. The twin is spawned without the purple stimm, so it stops there." },
	tw_warning_self_split_one_unchecked = { en = "Twins spawn loop: %s splits into %s. Check infinite spawn loops is off, so it keeps splitting forever." },
	tw_warning_self_split_two_prevented = { en = "Twins spawn loop: %s splits into 2 x %s. The twins are spawned without the purple stimm, so it stops there." },
	tw_warning_self_split_two_unchecked = { en = "Twins spawn loop: %s splits into 2 x %s. Check infinite spawn loops is off, so the number of enemies doubles with every generation, forever." },
	tw_warning_no_stim_animation = { en = "%s has no stim animation: the purple stimm is applied directly when it spawns, using the chance below." },
	tw_a = { en = "Twin 1" },
	tw_b = { en = "Twin 2" },
	tw_row_default = { en = "The game's split: %s" },
	tw_sa = { en = "Twin 1 splits again" },
	tw_sb = { en = "Twin 2 splits again" },
	tw_sa_info = { en = "It has Twins too, with these same settings, while Generations allow." },
	tw_sb_info = { en = "It has Twins too, with these same settings, while Generations allow." },
	tw_ka = { en = "Twin 1 keeps this row's mods" },
	tw_kb = { en = "Twin 2 keeps this row's mods" },
	tw_ka_info = { en = "Its modifiers, custom stats, colour and boss bar. Off: a plain enemy." },
	tw_kb_info = { en = "Its modifiers, custom stats, colour and boss bar. Off: a plain enemy." },
	tw_gen = { en = "Generations" },
	tw_gen_info = { en = "How many times a chain splits, 1 to %s. 1: only this row's enemies split; their twins never do." },
	tw_popup_title = { en = "%s: type an enemy" },
	tw_popup_hint = { en = "An enemy (\"poxburster\", \"crusher\"), \"none\", or empty for the game's own split." },
	tw_popup_unknown = { en = "\"%s\" is not an enemy Twins can spawn." },
}

-- The mod's menu in the Nurgle palette (2026-10-05, the user): the title in rot green and pus yellow, every section header in
-- one of the Plague colours. Only the colour tags are added; the words stay as above.
local function tint(key, colour) L[key].en = "{#color(" .. colour .. ")}" .. L[key].en .. "{#reset()}" end

L.mod_name.en = "{#color(128,160,52)}The Grandfather's {#color(196,182,84)}Tarot{#reset()}"

-- the version beside the name and at the start of the description (catalog/version.lua)
do
	local ok, version = pcall(function ()
		return get_mod("GrandfathersTarot"):io_dofile("GrandfathersTarot/scripts/mods/GrandfathersTarot/catalog/version")
	end)

	if ok and type(version) == "string" then
		L.mod_name.en = L.mod_name.en .. "  {#color(150,146,128)}v" .. version .. "{#reset()}"
		L.mod_description.en = "Version " .. version .. ". " .. L.mod_description.en
	end
end
tint("group_timing", "128,160,52")
tint("group_spawn", "196,182,84")
tint("group_multipliers", "150,118,62")
tint("group_controls", "104,150,96")
tint("group_hud", "176,140,48")
tint("group_spread", "140,170,80")
tint("group_twins", "150,60,160")
tint("group_twins_bosses", "150,60,160")
tint("group_twins_enemies", "150,60,160")
tint("group_twins_reset", "150,60,160")

-- Twins: the names of the bosses and enemies in its dropdowns (the game's own localized name when it resolves)
do
	local ok, catalog = pcall(function ()
		return get_mod("GrandfathersTarot"):io_dofile("GrandfathersTarot/scripts/mods/GrandfathersTarot/twins/catalog")
	end)

	local function display_name(entry)
		local resolved, text = pcall(Localize, entry.loc)

		if resolved and type(text) == "string" and text ~= "" and string.sub(text, 1, 1) ~= "<" then
			return text
		end

		return entry.name
	end

	if ok and type(catalog) == "table" then
		for _, list in ipairs({ catalog.bosses, catalog.enemies, catalog.extra_spawnable }) do
			for _, entry in ipairs(list) do
				local name = display_name(entry)

				L["tw_twin_" .. entry.id] = { en = name }
				L["tw_boss_" .. entry.id] = { en = name }
				L["tw_enemy_" .. entry.id] = { en = entry.stim and name or (name .. " [!]") }
			end
		end
	end
end

return L
